components/CodeForm.tsx
pages/welcome.tsx
styles/theme.ts

Fixing minor mobile styling issues

Mobile styles tweaks

---

common/therapyFaqs.tsx
components/Faqs.tsx
components/Footer.tsx
components/Header.tsx
components/ImageTextGrid.tsx
components/NavigationDrawer.tsx
components/PartnerHeader.tsx
components/TopBar.tsx
messages/shared/en.json
messages/shared/es.json
messages/therapyBooking/en.json
messages/therapyBooking/es.json
pages/index.tsx
pages/register.tsx
pages/therapy-booking.tsx
pages/therapy-confirmation.tsx
pages/welcome.tsx

Add therapy confirmation page and refactor alt messages

Staging release: Therapy confirmation page + alt refactor (#21)

---

app/api.ts
app/partnerAccessSlice.tsx
app/partnerSlice.tsx
app/userSlice.tsx
common/authGuard.tsx
components/RegisterForm.tsx
pages/therapy-booking.tsx

Completes `AuthGuard` to get the users data `/users/me` when a user attempts to access a protected page and they have a token in localstorage.
May be forcing the app into static page generation so should be reviewed for other solutions in the future

Auth guard persist / refetch user

---

app/api.ts
app/partnerAccessSlice.tsx
app/partnerSlice.tsx
app/userSlice.tsx
common/authGuard.tsx
components/RegisterForm.tsx
pages/therapy-booking.tsx

Staging release: Auth guard persist / refetch user (#28)

---

app/partnerAccessSlice.tsx
app/partnerSlice.tsx
app/userSlice.tsx
components/TopBar.tsx
components/UserMenu.tsx
messages/auth/en.json
messages/navigation/en.json

Logout button and new user menu for it to live in.
Clears state and accessToken before redirecting to `/login`

Logout from user menu

---

components/Header.tsx
components/LeaveSiteButton.tsx
components/PartnerHeader.tsx
messages/auth/en.json
messages/auth/es.json
messages/shared/en.json
messages/shared/es.json
pages/_app.tsx
pages/therapy-booking.tsx
styles/theme.ts

Adds a fixed button to leave the site quickly. Also replaces the location so going back doesn't reveal the bloom site.

Leave site button

---

components/LeaveSiteButton.tsx
messages/auth/en.json
pages/register.tsx

Added link to login page, on the register page

Redirect to login

---

components/TopBar.tsx
messages/index/en.json
messages/welcome/en.json
pages/index.tsx
pages/login.tsx
pages/therapy-booking.tsx
utils/logEvent.ts

Various fixes incl a build error for importing Next router incorrectly

Build fixes - next router

---

components/LoginForm.tsx
messages/auth/en.json

Fixes login error from recent changes in #72

Fix login error

---

components/CourseCard.tsx
components/CourseIntroduction.tsx
components/LeaveSiteButton.tsx
components/SessionContentCard.tsx
config/storyblok.ts
messages/courses/en.json
package.json
pages/auth/login.tsx
pages/auth/register.tsx
pages/auth/reset-password.tsx
pages/courses/[slug].tsx
pages/courses/[slug]/[sessionSlug].tsx
pages/courses/index.tsx
pages/welcome.tsx
styles/theme.ts

Styles tweaks and build fix for dependency

Course style tweaks + dep fix

---

app/coursesSlice.tsx
components/Footer.tsx
constants/enums.ts
constants/partners.tsx
messages/shared/en.json

Updates footer to include partner logo/details dynamically based on the user's partnerAccesses

Dynamic footer

---

pages/auth/login.tsx
pages/auth/register.tsx
pages/courses/[slug]/[sessionSlug].tsx
pages/courses/index.tsx

Minor style fixes following last release

Staging release: Release style tweaks

---

messages/welcome/en.json
pages/welcome.tsx

Add missing link on welcome page

Add link to resources

---

components/Footer.tsx

Temporary fix to add bumble details to footer

Add bumble footer to welcome

---

messages/auth/es.json
messages/courses/es.json
messages/index/es.json
messages/navigation/es.json
messages/partnerAdmin/es.json
messages/shared/es.json
messages/therapy/es.json
messages/welcome/es.json
next.config.js

Adds back Spanish to config locales and add back es.json files with a few strings translated.

Add spanish

---

components/NavigationMenu.tsx
pages/courses/[slug].tsx
pages/courses/[slug]/[sessionSlug].tsx
pages/therapy/book-session.tsx
utils/therapyAccessGuard.tsx

Refactor shorter way to use `.find()`

Refactor find

---

components/CourseCard.tsx
components/CourseIntroduction.tsx
components/Footer.tsx
components/Header.tsx
components/ImageTextGrid.tsx
components/NavigationDrawer.tsx
components/PartnerHeader.tsx
components/SessionCard.tsx
components/SessionContentCard.tsx
components/TopBar.tsx
pages/404.tsx
pages/500.tsx
pages/action-handler.tsx
pages/auth/login.tsx
pages/auth/register.tsx
pages/auth/reset-password.tsx
pages/courses/[slug].tsx
pages/courses/[slug]/[sessionSlug].tsx
pages/courses/index.tsx
pages/partner-admin/create-access-code.tsx
pages/therapy/book-session.tsx
pages/welcome.tsx
styles/common.ts
utils/authGuard.tsx
utils/partnerAdminGuard.tsx
utils/therapyAccessGuard.tsx

Refactors repeated flex styles into reusable `rowStyle` `columnStyle` and `centeredContainerStyle`

Refactor flex styles

---

components/cards/CourseCard.tsx
components/cards/SessionCard.tsx
components/common/ProgressStatus.tsx
components/video/CourseIntroduction.tsx
pages/courses/[slug]/[sessionSlug].tsx

Fixing small left over bugs from several refactors

Refactors fixes

---

components/layout/Footer.tsx

Improves the readability of the footer code and fixes bug related to duplicate partner footer blocks being included.

Refactor dynamic footer

---

components/storyblok/StoryblokImage.tsx
components/storyblok/StoryblokPageSection.tsx
components/storyblok/StoryblokRow.tsx
components/storyblok/StoryblokVideo.tsx
messages/welcome/en.json
messages/welcome/es.json
pages/meet-the-team.tsx
styles/globals.css
utils/richText.tsx

This PR adds components for new Storyblok "page_section" and "row"/"row_item" components. These are custom storyblok components which we've set fields for alignment, background colour, sizes etc.
Also includes refactors and tweaks to existing StoryblokImage and StoryblokVideo components

Storyblok Page Section + Row blocks

---

components/layout/Footer.tsx
components/storyblok/StoryblokQuote.tsx
pages/meet-the-team.tsx
utils/richText.tsx

Quote component for new Storyblok nestable Quote block. Includes speech icons before and after the `blockquote`
Likely the icons will be updated with a custom illustration.

Storyblok quote component

---

components/cards/CourseCard.tsx
components/cards/SessionCard.tsx

CardActionArea href links ignore internationalisation so have made the component a link component which seems to fix it

150322-1608/ fix link in Cards for internationalisation

---

components/forms/CodeForm.tsx
components/forms/CreateAccessCodeForm.tsx
components/forms/LoginForm.tsx
components/forms/RegisterForm.tsx
components/forms/ResetPasswordForm.tsx
components/layout/LeaveSiteButton.tsx
package.json
styles/theme.ts
yarn.lock

This PR adds a loading state to the forms, with a `LoadingButton` giving feedback when the form is loading. 
Some additional styles were added for disabled buttons, as the `LoadingButton` styles default to grey which looked off!

Form loading state + button

---

components/cards/SessionContentCard.tsx
components/layout/NavigationMenu.tsx
components/layout/TopBar.tsx
components/storyblok/Faqs.tsx
pages/courses/[slug]/[sessionSlug].tsx

Small changes based on feedback

V1 release tweaks 2

---

pages/courses/[slug].tsx
pages/courses/[slug]/[sessionSlug].tsx

Just something I noticed. The breadcrumbs weren't maintaining locale and they needed to be made into link components"

Make breakcrumbs links for internationalisation

---

components/forms/WelcomeCodeForm.tsx
constants/partners.ts

Bug left when adding badoo, forgot to add to getPartnerContent

Fix badoo content

---

components/layout/NavigationMenu.tsx
components/layout/TopBar.tsx

Makes bloom logo in topbar/nav link to the partner's welcome page, based on the users state.
Also reorders the menu items

Bloom logo partner welcome

---

messages/account/es.json
messages/auth/es.json
messages/welcome/es.json

Apply code translations

---

components/cards/CourseCard.tsx
components/cards/SessionCard.tsx
components/cards/SessionContentCard.tsx
components/common/ProgressStatus.tsx
components/course/CourseIntroduction.tsx
components/course/CourseStatusHeader.tsx
components/forms/ApplyCodeForm.tsx
messages/account/es.json
messages/auth/es.json
messages/courses/en.json
messages/courses/es.json
messages/welcome/es.json
pages/auth/register.tsx
pages/courses/[slug].tsx
pages/courses/[slug]/[sessionSlug].tsx
pages/courses/index.tsx
styles/common.ts
styles/globals.css
styles/theme.ts
utils/courseLiveStatus.ts
utils/dateTime.ts
utils/logEvent.ts
utils/richText.tsx

See squashed commits for changes.

Staging release: live courses, card padding, firebase event params

---

components/cards/TeamMemberCard.tsx
components/common/ContentUnavailable.tsx
components/storyblok/DynamicComponent.tsx
components/storyblok/StoryblokStatement.tsx
constants/partners.ts
messages/partnership/en.json
messages/partnership/es.json
pages/courses/[slug].tsx
pages/partnership/[partnerName].tsx
utils/helper-types/translations.d.ts
utils/richText.tsx

Ticket [link](https://www.notion.so/chayn/Add-partnership-page-8118f3c1119945399ae941c736fc6a9e)
Figma [design](https://www.figma.com/file/x1hNLgjjXfyzyAMUjMk0gd/Bloom-platform-designs?node-id=8382%3A55879)
I added a new StoryblokStatement component for the text starting with "This progreamme..." since it required more specific formatting than plain text. 
Also fixed a bug in the meet the team page. This means meet the team page is now visible - however the alignments aren't quite correct yet. 
Let me know thoughts!

170322-1604 / add partnership page

---

components/layout/Footer.tsx

The footer partner containers weren't flexing well with there was 2+ partners. Small styles tweaks to improve

Footer flex tweaks

---

components/cards/TeamMemberCard.tsx
components/layout/Footer.tsx
components/layout/LanguageMenu.tsx
components/layout/NavigationMenu.tsx
components/layout/TopBar.tsx
components/layout/UserMenu.tsx
messages/navigation/en.json
messages/navigation/es.json
pages/_app.tsx
pages/courses/[slug]/[sessionSlug].tsx

See squashed commits/PRs for changes

Staging release: fix password reset flow, meet the team nav, styles fixes

---

components/crisp/CrispButton.tsx
messages/courses/en.json
messages/courses/es.json
next.config.js
pages/courses/[slug]/[sessionSlug].tsx

Ticket [link](https://chayn.notion.site/Update-Reflect-with-us-text-1349b3c0326648eeb83a38a6256855a5)
As we are not a crisis service, the text was updated to make clear to users when they start the 1-1 chat.
Have added spanish translation as well.

Update reflect with us text

---

components/forms/ApplyCodeForm.tsx
components/forms/LoginForm.tsx
components/forms/RegisterForm.tsx
constants/faqs.ts
guards/partnerAdminGuard.tsx
guards/therapyAccessGuard.tsx
messages/shared/en.json
messages/shared/es.json
pages/partnership/[partnerName].tsx
pages/therapy/book-session.tsx
pages/therapy/confirmed-session.tsx

Making the typeform feedback form translatable

Add spanish feedback typeform

---

messages/courses/en.json
messages/courses/es.json
pages/courses/[slug].tsx

Adding 'Back To Courses' button text to the messages as it is currently untranslatable

Make back to courses translatable

---

pages/_app.tsx
pages/partnership/[partnerName].tsx

- added partnership page to list of public places in the auth guard 
- removed the partner access guard from the partnership pages

Make partnership pages public

---

package.json
yarn.lock

A tester to just see if this helps! A warning came up before the memory overload logged. It said we shoudl use sharp for image optimisation. I am just adding to staging to see what happens and test. Let me know your thoughts
https://nextjs.org/docs/messages/sharp-missing-in-production

Add sharp package for image optimisation

---

messages/account/es.json

https://www.notion.so/chayn/Spanish-translations-for-apply-a-code-page-1d931b2094a144b3aa2d25db84f934ef

Add spanish translations apply a code

---

next.config.js

Add redirects for login and welcome page

Redirect welcome and login pages to courses

---

messages/account/en.json

Update apply a code translation

---

components/layout/UserMenu.tsx

Hide apply a code page from partner admins

Only show apply a code to non partner admins

---

components/layout/Footer.tsx

See https://www.notion.so/chayn/Double-Bumble-logo-in-footer-e00b0c7de4df4b37a73621d0cff22771

Fix double logo footer bug

---

components/layout/LanguageMenu.tsx

Temporary patch to remove hindi from navigation

Remove hindi from language navigation

---

.github/workflows/merge-to-main.yml

- all this one does is deploy when you push to main

Create merge to main workflow

---

components/forms/AboutYouSetBForm.tsx
components/forms/AboutYouSetCForm.tsx
messages/account/en.json
messages/account/es.json
messages/account/hi.json
pages/account/about-you.tsx

relates to https://www.notion.so/chayn/Allow-switching-between-forms-in-account-about-you-page-21456ad8415e4a20b48e9edb3b4160d9 
- this PR is just to enable switching between forms based on the url.

Create b and c about you forms

---

.github/workflows/pull-request.yml
package.json

Rename the pipeline and remove staging from the list of branches to run this on

Update pull request pipeline

---

.github/workflows/merge-pr-develop.yml

From the console.log in the test run, the pulls.list request returns a full response with status. So I want to check the status and then check the data.

Fix merge pr onto develop workflow

---

jest.config.js
package.json
pages/about-our-courses.tsx
pages/partner-admin/create-access-code.tsx
utils/formatPartnerAccess.test.ts
utils/formatPartnerAccesses.ts
utils/logEvent.ts
yarn.lock

- Fix jest testing
- ensure partners are coming through in analytics

Partner analytics

---

messages/account/es.json

Change layout of spanish about you messages as they were in the wrong place

Fix spanish messages for about you forms

---

components/forms/AboutYouDemographicForm.tsx
components/forms/AboutYouSetAForm.tsx
components/forms/AboutYouSetBForm.tsx
components/forms/AboutYouSetCForm.tsx
components/forms/ApplyCodeForm.tsx
components/forms/CreateAccessCodeForm.tsx
components/layout/Footer.tsx
pages/about-our-courses.tsx
pages/account/about-you.tsx
pages/courses/[slug].tsx
pages/courses/[slug]/[sessionSlug].tsx
pages/courses/index.tsx
pages/meet-the-team.tsx
pages/partner-admin/create-access-code.tsx
pages/therapy/book-session.tsx
pages/therapy/confirmed-session.tsx

- note this is just supplying partnerAdmin to the getEventData function.
- I have chosen not to look into the various interpretations of how eventData is set. Sometimes in useeffect and sometimes not

Ensure all getEventData functions are passed partnerAdmin

---

components/forms/AboutYouSetBForm.tsx
components/forms/AboutYouSetCForm.tsx
utils/getCourseData.test.ts
utils/getCourseData.ts

- function to extract course data from user 
- added the course data to the request

[High level] Add course data to survey forms

---

components/head/OpenGraphMetadata.tsx

Add an absolute URL for og:image metadata

---

components/head/OpenGraphMetadata.tsx

Add twitter specific metadata

---

components/head/OpenGraphMetadata.tsx

Update twitter specific meta tags

---

components/head/OpenGraphMetadata.tsx

Reduce twitter description character limit

---

components/head/OpenGraphMetadata.tsx

Update twitter description to be shorter

---

pages/courses/[slug].tsx
pages/courses/[slug]/[sessionSlug].tsx
utils/hasAccessToPage.test.ts
utils/hasAccessToPage.ts

- Refactor how access is done
- Allow partner admins to see partner courses

Refactor access and allow admins on partner pages

---

components/common/ImageTextGrid.tsx
components/common/Link.tsx
components/layout/Header.tsx
components/layout/PartnerAdminHeader.tsx
components/layout/PartnerHeader.tsx
components/storyblok/StoryblokImage.tsx
constants/partners.ts
next-env.d.ts
package.json
tsconfig.json
yarn.lock

Upgraded next
fixed type errors. 
next/image has changed to nesting images inside spans rather than inside divs. I had to change some styling to accommodate this
Removed resolutions as thought best to reset back to neutral

[FYI] Upgrade to next 12 and fix images

---

components/storyblok/StoryblokVideo.tsx

See https://support.google.com/youtube/answer/171780?hl=en-GB#zippy=%2Cturn-on-privacy-enhanced-mode

Make youtube videos non-cookie versions

---

.github/workflows/merge-pr-develop.yml
.gitignore
components/forms/ResetPasswordForm.tsx
components/layout/Consent.tsx
tests/cypress/integration/cookie-consent.spec.tsx
tests/cypress/integration/reset-password.spec.tsx

Add cypress ci workflow

---

.github/workflows/merge-pr-develop.yml

@swetha-charles 
A couple of links I was following if you decide to pick this up 
https://github.com/vercel/next.js/issues/36221
We have a custom document apparently https://nextjs.org/docs/advanced-features/custom-document
Ideas I had:
- ensure we have the same browser
- ensure the same node version
- ensure the same next version
- ensure the same cypress version

Update cypress ci config for new structure

---

.github/workflows/build-and-test.yml
.github/workflows/checks-on-pr.yml
.github/workflows/deploy-to-prod.yml
.github/workflows/deploy-to-staging.yml
.github/workflows/manual-deploy-prod.yml
.github/workflows/manual-deploy-staging.yml

2d638a6cc1 / Restructure github actions

Rename manual trigger actions to be more explicit

---

README.md
config/featureFlag.test.ts
config/featureFlag.ts
pages/courses/index.tsx

The env vars have already been set up in heroku in staging and prod

Enable courses

---

pages/courses/index.tsx

Missed removing this unneeded filter method.
3d3abfa9a6 / Enable courses in french

Remove unnecessary code

---

README.md

189f3a5543 / Update bloom README's for volunteers

Add volunteer specific info to README

---

constants/enums.ts
next.config.js

This enables Portugese on the bloom website (staging and prod)

1e19f2b346 / Enable portugese

---

app/coursesSlice.tsx
components/crisp/CrispScript.tsx
components/crisp/utils/createCrispProfileData.test.ts
components/crisp/utils/createCrispProfileData.ts

- for some reason sessino.completed was set as a string. I changed it to boolean and it didn't seem to have any impact
- added visitor data on load

[High level] update visitor data when user visits bloom

---

components/banner/UserResearchBanner.tsx
components/layout/Header.tsx
components/layout/TopBar.tsx

Move user research banner into header

---

components/banner/UserResearchBanner.tsx

5906fb0ddf / Create user research banner

Add user specific cookie

---

components/banner/UserResearchBanner.tsx

5906fb0ddf / Create user research banner

Fix incorrect cookie key

---

components/layout/NavigationMenu.tsx

**TASK**:
- if a user goes to /auth/login, check they are logged in.
- if they are logged in redirect them to the /courses page.

Redirect loggedin user

---

pages/courses/[slug]/[sessionSlug].tsx

3fe498800f / Investigate rollbar error: cannot read property 'id' of undefined

Add log to better understand cause of rollbar error

---

guards/publicPageDataWrapper.tsx
pages/_app.tsx

This is necessary to ensure the user's view of the nav bar is correct even on public pages.
263f7236b6 / Therapy not visible on homepage nav after login

Add function to pull user data on public pages

---

components/layout/AppBarSpacer.tsx
components/layout/Header.tsx
components/layout/LeaveSiteButton.tsx
components/layout/PartnerHeader.tsx
components/layout/TopBar.tsx
pages/_app.tsx

- Added a spacing component to keep the spacing at the top consistent so we only need to touch one place as the nav changes
- also removed unecessary top padding

Add app bar spacer to remove extra padding from headers

---

components/layout/NavigationDrawerLinks.tsx
components/layout/SecondaryNav.tsx
components/storyblok/StoryblokFaqs.tsx

This adds chat in the second nav and drawer in mobile view.

Add chat to second nav

---

app/userSlice.tsx
components/layout/LanguageMenu.tsx
components/layout/NavigationMenu.tsx
components/layout/SecondaryNav.tsx
components/layout/TopBar.tsx
components/layout/UserMenu.tsx
cypress/integration/navigation.cy.tsx
cypress/support/commands.js
cypress/support/index.d.ts
guards/authGuard.tsx
guards/publicPageDataWrapper.tsx

Racy conditions created by user.loading being instantiated as true. I made a change. Let me know what you think

Cypress tests navbar

---

pages/auth/register.tsx

- add partner branding to register page

Fix fruitz views

---

components/cards/SessionCard.tsx
components/session/SessionProgressDisplay.tsx
pages/courses/[slug].tsx
pages/courses/image-based-abuse/index.tsx
utils/helper-types/storyblok.d.ts

- Created new component SessionProgressDisplay which encapsulates logic to display session progress
- Removed this logic from /courses/[slug]
- Removed this logic from /courses/image-based-abuse/index
- Plugged in new component in SessionCard which is used in both /courses/[slug] and  /courses/image-based-abuse/index

FYI: Refactor shared session progress

---

components/course/CourseHeader.tsx
pages/courses/[slug].tsx
pages/courses/image-based-abuse/index.tsx
utils/courseProgress.ts

- Refactored a CourseHeader which is now used in both the IBA and regular course page 
- Refactored logic which determines course progress. This function is now used in both the IBA and regular course page

Refactor shared logic on course pages

---

components/session/MultipleBonusContent.tsx

dbc4f6ca0e / IBA: Add title for bonus session card

Use storyblok title for bonus content card

---

components/storyblok/StoryblokAccordion.tsx

- accordion title JSON has changed and you no longer need a resolver to render

Ensure accordion title is an A3

---

components/layout/SecondaryNav.tsx
components/storyblok/StoryblokAccordion.tsx
components/storyblok/StoryblokAudio.tsx
utils/richText.tsx

- add padding below audio component
- increase max-width to accommodate for extra large column sizes
- fix bug on secondary nav

Grounding design changes

---

cypress/integration/activities.cy.tsx

- Basic test to cover clicking on the activities navigation 
- Clicking on an accordion and seeing it open and checking the content inside

Activities cypress test

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general-issue-template.md

- Proposition for issue templates

Update issue templates

---

config/simplybook.ts

For some reason Simplybook has weird ids for additional fields and it changes according to environment

Add env toggle for simplybook Additional field id

---

components/layout/LanguageMenu.tsx
config/featureFlag.ts
constants/enums.ts
next.config.js

- Add german behind feature flag
- Filter german out of language drop down on production

Enable german behind feature flag

---

components/layout/NavigationDrawerLinks.tsx
components/layout/SecondaryNav.tsx
config/featureFlag.ts

- remove feature flag that was hiding grounding and activities pages from navigation

Remove feature flag for grounding and activities

---

messages/account/hi.json
pages/courses/[slug]/[sessionSlug].tsx

- Removing messages and unused variables from code
- These were left behind when deactivating the session4 impact survey

Clean up unused code that was left when deactivating impact survey

---

.github/workflows/build-and-test-prs.yml
.github/workflows/cypress-test.yml
.github/workflows/deploy-to-prod.yml
.github/workflows/deploy-to-staging.yml

- remove repeated build and tests
- Update versions of actions/checkout actions/setup-node actions/cache

Actions updates

---

.github/workflows/deploy-to-staging.yml
components/storyblok/StoryblokAudio.tsx
components/storyblok/StoryblokVideo.tsx
components/video/Video.tsx
cypress/integration/activities.cy.tsx
cypress/integration/user-course-session-behaviour.cy.tsx
package.json
yarn.lock

- Bug that seems to be happening on old Cypress versions in package.json and actions with Chrome 117 so just updating everything and then will play with a workaround in another PR https://github.com/cypress-io/cypress/issues/27804#issuecomment-1721476731
-  Lazyloading youtube to speed up page load - thinking this might help generally but also with cypress tests
- Some cypress tests are racy because of page load speed so added longer timeouts. Hopeful general performance changes will helpf this in the future

Debug cypress tests

---

README.md

Add link to CONTRIBUTING.md file in README.md

---

README.md
docs/key-concepts.md

Moved Key Concepts section from README.md to a new file "key-concepts.md" inside /docs folder in root directory,

Fixed issue 617 

---

pages/sitemap.xml.tsx
public/robots.txt

Solves issue #610 .
Also added a sitemap.xml.tsx file and linked it to robots.txt. Please let me know if you want me to edit/remove the sitemap file.

added robots.txt file with disallowed urls. 

---

components/layout/PartnerAdminHeader.tsx
messages/admin/de.json
messages/admin/en.json
messages/admin/es.json
messages/admin/fr.json
messages/admin/hi.json
messages/admin/pt.json
messages/partnerAdmin/en.json
pages/admin/dashboard.tsx

- updating copy for new therapy session form and super admin dashboard. Small update to partner admin dashboard

Update admin dashboard copy

---

README.md

Fixes #623.
Changed the text as written in the issue description and updated the link from the form page to the volunteer info page.

Linked volunteer page in Readme file

---

components/layout/LanguageMenu.tsx
config/featureFlag.ts

Issue number not held in Github 
- Removed a filter in the nav bar that excluded german
- Removed feature flag 
We are releasing a german language version of the site  to the public

Remove german feature flag and nav bar filter

---

styles/hotjar.css

NPS styles - more specific selectors

---

styles/hotjar.css

NPS styles - more specific selectors 2

---

pages/_app.tsx
styles/hotjarNPS.css

NPS styles - more specific selectors 3

---

styles/hotjarNPS.css

NPS styles - more specific selectors 4

---

components/forms/UpdateTherapyAdminForm.tsx

On Notion - N/A
- only getting back users with partnerAccesses that have featureTherapy as true. 
- Checking that the partner access that we update has featureTherapy Activated
- I had implented the super admin dashboard therapy session form with a bug where it was adding therapySessions to partnerAccesses that did not have featureTherapy as active.

fix: only update featureTherapy partnerAccess on super admin therapy dashboard

---

styles/hotjarNPS.css

NPS styles - more specific selectors 6

---

cypress/integration/activities.cy.tsx
cypress/integration/therapy-usage.cy.tsx

N/A
Increased some timeouts on cypress tests, to safeguard flakiness
- Cypress tests are flaky

fix: increase timeouts to improve cypress flakiness

---

components/forms/AboutYouDemographicForm.tsx
messages/account/de.json
messages/account/en.json
messages/account/es.json
messages/account/fr.json
messages/account/hi.json
messages/account/pt.json

N/A - ticket in notion. 
- Turned gender  freetext into a multiselect autocomplete form. 
- Help with analysing data. Free text format meant data cleaning was a challenge

feat: Gender input is now a multiselect not free text

---

pages/sitemap.xml.tsx

Closes issue #637 
Added ability to add dynamically generated coures routes to sitemap.xml .
Added dynamic routes to sitemap for better SEO 

Added dynamic courses routes to sitemap

---

components/banner/UserResearchBanner.tsx

N/A
- Only showing user research banners to certain partner users
- We are putting an ad out for a few days for user research participants.

feat: show user research banners to users

---

middleware.ts

N/A
test to see if I can fix the issue about redirects. wonddering if host vs hostname is the issue? Changed to temporary redirect because im worried about setting 301s until we are certain it is correct
http://bloom.chayn.co was redirecting to  the number host address...

fix: http-https redirect fix 2

---

package.json
yarn.lock

N/A
Downgraded next to 13.4.12 due to http->https issue
See -> https://github.com/vercel/next.js/issues/54133

Http https redirect fix 2

---

.github/workflows/create-release-pr.yml

Fixed incorrect dependency following previous update
Dependent job no longer exists

Fix github action dependency

---

.github/workflows/create-release-pr.yml

Fixes linting issue in new `create-release-pr` action

Fix github action lint

---

README.md

Updates README 
Duplicate work of (#706) completed by @kyleecodes , as the initial #706 commit was merged and then `develop` was reset to before it, to fix a branching issue.

Docs: Update README with env vars for external contributors

---

.github/workflows/cypress-release-test.yml

Changed branch syntax and fixed cypress-run: `needs` dependency

Fix cypress release tests

---

.github/workflows/cypress-release-test.yml
public/hotjarNPS.css

Restyle Hotjar NPS survey following updates to the widget

Restyle NPS survey

---

.github/workflows/codeql-analysis.yml

Enables the codeql action on pull requests made to `main` branch 
Previous change removing `push:` removed the action from `main` branch

Run codeql on main

---

components/storyblok/StoryblokQuote.tsx
components/storyblok/StoryblokSpacer.tsx
styles/globals.css

N/A
- Minor styling changes to storyblok carousel, spacer and quote component
- Improve styling

fix: minor styling tweaks for carousel and spacer

---

cypress/integration/initial-exploration.cy.tsx

N/A
- changed string cypress tst is looking for in initial-exploriation.cy.tsx 
- get cypress tests passing

fix: initial exploration cypress test

---

components/common/Quote.tsx

N/A
- adjusted the postion of the quotes in quote component
- implementation didn't match design.

fix: quote styling adjustments

---

.github/workflows/lighthouse-performance.yml
app/api.ts
components/forms/LoginForm.tsx
components/forms/RegisterForm.tsx
components/forms/ResetPasswordForm.tsx
components/layout/UserMenu.tsx
components/storyblok/StoryblokRow.tsx
config/firebase.ts
cypress/support/commands.js
guards/authGuard.tsx
guards/publicPageDataWrapper.tsx
package.json
pages/_app.tsx
utils/logEvent.ts
yarn.lock

Upgrades firebase from 9.9.2 to 10.7.1
As part of larger epic to improve bloom performance. This upgrade relates to a wider goal of reducing unused javascript - firebase 10.x uses modular api design so we can import only the functions we need, instead of the entire e.g. auth module.
Overall bundle reduced by 60kb but will also add performance gains to individual pages using firebase functions
See before and after bundle analysis:

Upgrade firebase to 10.7.1

---

cypress/support/commands.js

Fix cypress firebase

---

app/api.ts
app/coursesSlice.tsx
app/partnerAccessSlice.tsx
app/partnerAdminSlice.tsx
app/partnersSlice.tsx
app/store.ts
app/userSlice.tsx
components/forms/LoginForm.tsx
components/forms/RegisterForm.tsx
components/layout/UserMenu.tsx
hooks/store.ts
messages/auth/de.json
messages/auth/en.json
messages/auth/es.json
messages/auth/fr.json
messages/auth/hi.json
messages/auth/pt.json
package.json
yarn.lock

Updated redux packages to latest versions, and ensured the setup matched recommeneded.
Also improved user login/register erroring in testing
As part of wider epic to improve Bloom performance, most packages have been updated

Update Redux 

---

components/forms/LoginForm.tsx

Fixes graphql warning about redirect. The change was added in previous #773 
https://github.com/chaynHQ/bloom-frontend/security/code-scanning/9

Fix graphql redirect warning

---

components/course/CourseHeader.tsx
components/crisp/CrispScript.tsx
components/storyblok/StoryblokCoursePage.tsx
components/storyblok/StoryblokMeetTheTeamPage.tsx
components/storyblok/StoryblokSessionIbaPage.tsx
components/storyblok/StoryblokSessionPage.tsx
guards/authGuard.tsx
guards/publicPageDataWrapper.tsx
pages/_app.tsx
pages/about-our-courses.tsx
pages/account/about-you.tsx
pages/account/apply-a-code.tsx
pages/admin/dashboard.tsx
pages/partner-admin/create-access-code.tsx
pages/therapy/book-session.tsx
pages/therapy/confirmed-session.tsx

Fix useEffect dependencies recently broken by removing array (foolish copy error by myself!)
This bug was causing some analytics VIEWED events to send on reredenders, so analytics events would be spiked for the last 2 days

Fix events dependencies

---

public/hotjarNPS.css

Fixes hotjar styles following update to css classes

Fix hotjar styles

---

components/layout/Footer.tsx
components/storyblok/StoryblokRowColumnBlock.tsx

N/A 
- added 100% width to Box component outside Row 
See width bug below

Fix page size bug

---

pages/_app.tsx

Temporarily comment out custom hotjar styles to test if our styles are breaking the styling.
The styles were previously okay but recently (late December) became misaligned

Temp remove hotjar styles

---

pages/_app.tsx
public/hotjarNPS.css

Removed custom hotjar NPS **container** styles, as they were conflicting with new hotjar native styles
Fixes positioning issue seen below

Fix hotjar container styles

---

.github/workflows/cypress-release-test.yml
.github/workflows/cypress-test.yml
README.md
cypress/integration/partner-admin.cy.tsx

Clean up env vars for cypress test users and reset test account passwords
Many tests failing due to auth issues, attempting to fix

Fix tests + clean cypress env vars

---

.github/workflows/newrelic-release-tracking.yml
newrelic.js

Adds new relic config file instead of using env vars as the setup, which didn't seem to be registering
New Relic setup not being registered in previous setup - see #798 #808

Add newrelic config file

---

newrelic.js

Changed New Relic logging options to try to get browser monitoring working - see #808 
Browser monitoring is currently not working

verbose logging

---

pages/_document.tsx

Added resolve to wait for new relic connection before adding required headers
New relic browser monitoring wasnt working - see #808

New Relic fix - wait for connection

---

components/layout/HomeHeader.tsx
messages/shared/de.json
messages/shared/en.json
messages/shared/es.json
messages/shared/fr.json
messages/shared/hi.json
messages/shared/pt.json
pages/index.tsx
styles/theme.ts

N/A - part of homepage redesign
- Changed banner layout
- Background gradient 
- Button colour updates
- New redesign to make it clearer what bloom does

Homepage banner

---

components/storyblok/StoryblokSessionIbaPage.tsx
pages/auth/login.tsx

Fixed partner admin redirect when a user is on the login page and already logged in
Also fixed minor style issue on image-based-abuse session page
Failing test made us aware of this feature not working

Fix partner admin redirect

---

components/forms/LoginForm.tsx
components/layout/Footer.tsx
components/storyblok/StoryblokWelcomePage.tsx
constants/partners.ts
pages/auth/login.tsx
pages/partnership/[partnerName].tsx

Fixed redirect flow to be only on the login page
Login redirect conflict between `login` page and `LoginForm` component, causing extra redirects

Fix login redirect

---

components/layout/HomeHeader.tsx
constants/partners.ts

N/A in Notion
- Ensured the right logos are being shown on home page when logged out
- Fixed home page alt text
- partner logos were showing when they shouldn't
- error logs in the console about message

Footer and Home page banner fix

---

cypress/integration/initial-exploration.cy.tsx

N/A
Changed the text that cypress was looking out for on the home page
Home page text changed broke the cypress tests.

fix: initial-exploration test due to homepage rediesgn

---

cypress/integration/create-user.de.cy.tsx
cypress/support/commands.js
cypress/support/index.d.ts

N/A
Created a german create user test as a prototype
We currently have no testing in languages other than english. I wanted to create a prototype for how we will proceed doing this.

test: german create user test

---

.github/workflows/newrelic-release-tracking.yml

Changed newrelic CI action region setting from `US` to `EU` - our account is EU
New relic CI action started failing (previously worked) with error `403 response returned - please check your API key and region`

Fix newrelic ci region

---

components/storyblok/StoryblokCard.tsx
messages/shared/de.json
messages/shared/en.json
messages/shared/es.json
messages/shared/fr.json
messages/shared/hi.json
messages/shared/pt.json

N/A in notion
Enabled storyblok cards to be clickable links
Users think our cards are clickable so we are making them links

feat: make storyblok cards clickable links

---

components/forms/RegisterForm.tsx
components/storyblok/StoryblokCard.tsx
cypress/integration/create-user.cy.tsx

N/A
- small fixes to register flow to ensure users are shown correct errors when logging in
users were not being shown helpful error messages when things were going wrong with registering

fix: user register errors

---

components/storyblok/StoryblokAccordion.tsx
constants/events.ts

N/A
Added an event to the accordion which sends the title of the accordion to GA. 
We can more accurately track usage of grounding and activities pages.

feat: event for accordion including title

---

components/layout/Footer.tsx
constants/partners.ts
messages/shared/de.json
messages/shared/en.json
messages/shared/es.json
messages/shared/fr.json
messages/shared/hi.json
messages/shared/pt.json

N/A
Added github logo to my footer
Ensuring users can access all our social media outlets.

feat: add github logo to footer

---

components/common/Link.tsx
components/layout/Footer.tsx

Adds icon to every external link, indicating to the user that the link will direct them to an external site.

Add external link icon

---

components/cards/CourseCard.tsx
pages/courses/index.tsx

N/A
Displaying list of courses before you sign up
So users have a better sense of what we offer

feat: display courses when not signed in

---

.github/pull_request_template.md

**This PR serves as a test PR for new workflow permissions.**
N/A
Updated PR template with testing question.

Test: Workflow permissions (Updates PR template)

---

components/course/CourseHeader.tsx
components/storyblok/StoryblokSessionIbaPage.tsx

N/A
Fix breadcrumb background colour as the button background has disappeared into the section gradient. 
Fix breadcrumb background colour as the button background has disappeared into the section gradient. 
Yes

fix: breadcrumb background colour

---

cypress/integration/create-user.hi.cy.tsx
cypress/support/commands.js
cypress/support/index.d.ts
messages/auth/hi.json

https://github.com/chaynHQ/bloom-frontend/issues/840
I add the test "create user in hindi"
To prevent bugs, like it happend last time as I read on the issue.

Add hindi user create test

---

components/cards/CourseCard.tsx
components/common/ContentUnavailable.tsx
components/common/ImageTextColumn.tsx
components/common/ImageTextGrid.tsx
components/layout/Consent.tsx
components/layout/Footer.tsx
components/layout/Header.tsx
components/layout/HomeHeader.tsx
components/layout/PartnerAdminHeader.tsx
components/layout/PartnerHeader.tsx
components/layout/SecondaryNav.tsx
components/layout/TopBar.tsx
components/storyblok/StoryblokAccordion.tsx
components/storyblok/StoryblokCard.tsx
components/storyblok/StoryblokFaqs.tsx
components/storyblok/StoryblokImage.tsx
components/storyblok/StoryblokTeamMemberCard.tsx
constants/partners.ts
guards/partnerAdminGuard.tsx
guards/superAdminGuard.tsx
guards/therapyAccessGuard.tsx
pages/404.tsx
pages/500.tsx
pages/account/apply-a-code.tsx
pages/auth/login.tsx
pages/auth/register.tsx
pages/therapy/book-session.tsx
pages/therapy/confirmed-session.tsx

Migrated All next/legacy/image instances to next/image succesfully as per the docs
Migrated All next/legacy/image instances to next/image succesfully as per the nextjs docs

Migrate: next/legacy/image -> next/image

---

components/cards/CourseCard.tsx
components/common/ContentUnavailable.tsx
components/common/ImageTextColumn.tsx
components/common/ImageTextGrid.tsx
components/layout/Consent.tsx
components/layout/Footer.tsx
components/layout/Header.tsx
components/layout/HomeHeader.tsx
components/layout/PartnerAdminHeader.tsx
components/layout/PartnerHeader.tsx
components/layout/SecondaryNav.tsx
components/layout/TopBar.tsx
components/storyblok/StoryblokAccordion.tsx
components/storyblok/StoryblokCard.tsx
components/storyblok/StoryblokFaqs.tsx
components/storyblok/StoryblokImage.tsx
components/storyblok/StoryblokQuote.tsx
components/storyblok/StoryblokTeamMemberCard.tsx
constants/partners.ts
guards/partnerAdminGuard.tsx
guards/superAdminGuard.tsx
guards/therapyAccessGuard.tsx
pages/404.tsx
pages/500.tsx
pages/_document.tsx
pages/account/apply-a-code.tsx
pages/auth/login.tsx
pages/auth/register.tsx
pages/therapy/book-session.tsx
pages/therapy/confirmed-session.tsx

https://github.com/chaynHQ/bloom-frontend/issues/921
Updated next/image import statements and style prop code for migrating to next 13.
Resolves the next/image error using [Nextjs codemods](https://nextjs.org/docs/messages/next-image-upgrade-to-13).

Fix: Next/image warnings after import upgrade

---

components/storyblok/StoryblokAccordion.tsx

N/A
Sent user data with events for GA so we could split accordion usage by partner

fix: send partner data in GA accordion open event

---

components/head/OpenGraphMetadata.tsx

https://github.com/chaynHQ/bloom-frontend/issues/916
Updated twitter and general description text to match text provided in issue

Updated general and twitter sharing preview text

---

cypress/integration/user-account-settings.cy.tsx

Fixed tests introduced in #900

Fix account page tests

---

.github/workflows/cypress-release-test.yml
components/forms/ApplyCodeForm.tsx
components/forms/CreateAccessCodeForm.tsx
components/forms/CreatePartnerAdminForm.tsx
components/forms/LoginForm.tsx
components/forms/RegisterForm.tsx
components/forms/UpdateTherapyAdminForm.tsx
components/forms/WhatsappSubscribeForm.tsx
components/forms/WhatsappUnsubscribeForm.tsx
components/session/SessionCompleteButton.tsx
components/storyblok/StoryblokSessionIbaPage.tsx
components/storyblok/StoryblokSessionPage.tsx
cypress/integration/therapy-usage.cy.tsx
cypress/support/commands.js
guards/AuthGuard.tsx
hooks/useLoadUser.ts
package.json
yarn.lock

Adds state update to end user loading flow, as is in the `LoginForm` component
Fixes `useLoadUser` rerendering causing `userResourceIsSuccess` to never be reached
Fixes `'data' in response` as this was now causing errors in vercel - unsure as to why these were thrown now
Tests were failing due to loading state not being completed

Fix new auth flow

---

app/api.ts
components/forms/ResetPasswordForm.tsx
components/head/RollbarScript.tsx

Minor fixes to prevent user errors being logged

Minor auth flow fixes

---

pages/auth/login.tsx

Uses token instead of userId for login page redirect - to match user menu
Potential loop issue with state and redirecting login -> courses -> login

Fix potential auth loop

---

components/cards/SessionContentCard.tsx
components/common/Faqs.tsx
components/course/CourseHeader.tsx
components/course/CourseIntroduction.tsx
components/crisp/CrispButton.tsx
components/forms/RegisterForm.tsx
components/session/MultipleBonusContent.tsx
components/session/SessionCompleteButton.tsx
components/video/Video.tsx
utils/logEvent.ts

Fixed bug on `getEventUserData` that was causing the createUser functionality to fail and not complete -> causing the user to not be logged in after registering.
Also fixes error [#103 Error: Cancel rendering route](https://app.rollbar.com/a/chayn/fix/item/bloom-frontend/103)

Fix user register bug + router cancel

---

cypress/integration/user-account-settings.cy.tsx

Fixes new email reminders form test, to reset the value back to the original value
On the second run of the test the value is set to the previously set value

Fix email reminder form test

---

components/cards/AccountActionsCard.tsx
components/forms/ConfirmDialog.tsx
components/forms/ProfileSettingsForm.tsx
components/forms/ResetPasswordForm.tsx
cypress/integration/delete-user.cy.tsx
cypress/integration/user-update-email.cy.tsx
guards/AuthGuard.tsx
messages/account/de.json
messages/account/en.json
messages/account/es.json
messages/account/fr.json
messages/account/hi.json
messages/account/pt.json
pages/account/settings.tsx
styles/theme.ts

N/A
Enabled users to delete their account and reset their password form the account page
Because we were having to do this manually and it is much for efficient for them to self serve. 
Yes and added more

Delete user and reset password 

---

.github/workflows/build-and-test-prs.yml
CYPRESS.md
README.md

Configures New Relic variables for contributors, GitHub Actions, and updates docs.

Fix: Configure New Relic Variable

---

cypress.config.ts

- Directions for running tests are in the README.md 

Fix reset password test

---

components/forms/RateSessionForm.tsx
cypress/integration/user-course-session-behaviour.cy.tsx
messages/courses/de.json
messages/courses/en.json
messages/courses/es.json
messages/courses/fr.json
messages/courses/hi.json
messages/courses/pt.json

N/A
- Small fixes to the sessionFeedback flow 
- Updating spacing
- Adding translations
responding to review of feedback flow from PM
Yes

fix: session feedback updates before release

---

CONTRIBUTING.md

Updated the CONTRIBUTING.md file under the "What kind of contributions does Chayn want?" section to correct a typo and update the list of contributions Chayn is looking for.
The changes were made to fix a spelling mistake in the word "documentation" and to ensure the contribution guidelines are clear and up-to-date with the types of contributions Chayn values.
No code changes were made, so no tests were required to be run
- Directions for running tests are in the README.md 
Before submitting, check …

Update contributing guidelines with additional contributions and fix typo

---

pages/courses/image-based-abuse-and-rebuilding-ourselves/[sessionSlug].tsx

#1060 
Added the same form to the Image based abuse course
As requested by ticket
Yes, but unable to run tests locally yet due to database issue mentioned in ticket discussion

Added feedback form to image based abuse page

---

CONTRIBUTING.md
messages/shared/de.json
messages/shared/hi.json
messages/shared/pt.json

Update footer "Funded by" translation strings following review from our translators

Update footer funded by translations

---

README.md
cypress/support/commands.js

Ensures NEXT_PUBLIC_API_URL always excludes trailing `/`
Inconsistency between staging and prodcuction path

Fix api url env var

---

.gitignore
messages/shared/de.json
messages/shared/es.json
messages/shared/fr.json
messages/shared/hi.json
messages/shared/pt.json

#913 
Ran script, adding translations where missing (from google translate)
As requested by ticket

Ticket-913 added missing translations after checking with script

---

cypress/integration/tests/maintenance.cy.tsx

#1089 
Created maintenance e2e test for english version
Yes

Maintenance e2e test

---

.github/pull_request_template.md
BLOOM_USERS.md
CONTRIBUTING.md
CYPRESS.md
README.md

N/A
New Cypress env var directions, updated README, Contributing Guidelines, and pull request template. 
- Directions for running tests are in the README.md 

Docs: Update OSS community directions and env vars

---

components/storyblok/StoryblokCoursePage.tsx
components/storyblok/StoryblokSessionIbaPage.tsx
components/storyblok/StoryblokSessionPage.tsx
cypress/integration/tests/initial-exploration.cy.tsx
cypress/integration/tests/register-partner-without-code.cy.tsx
utils/hasAccessToPage.test.ts
utils/hasAccessToPage.ts

N/A
Improved cypress tests to test availble course content for each type of user
Updated hasAccessToPage to take into account whether a user is logged in

Fix page access cypress tests

---

pages/messaging.tsx

Update messaging storyblok slug following #1142

Fix messaging storyblok slug

---

cypress.config.ts
cypress/integration/tests/user-messaging.cy.tsx

Fixes messaging tests following #1142

Fix messaging tests

---

components/layout/PrimaryNavigationDrawerLinks.tsx
components/layout/SecondaryNav.tsx
messages/navigation/fr.json
styles/globals.css

Updated french navigation string for "messaging" - this was the portuguese string

Fix french messaging nav string

---

.github/workflows/community-issue-comment.yml
.github/workflows/community-stale-management.yml

Lint actions - auto formatted by IDE. Submitted to test cypress env vars

Lint actions

---

components/head/DefaultHeadMetadata.tsx
components/storyblok/StoryblokCoursePage.tsx
components/storyblok/StoryblokMeetTheTeamPage.tsx
components/storyblok/StoryblokPage.tsx
components/storyblok/StoryblokSessionPage.tsx
components/storyblok/StoryblokWelcomePage.tsx
pages/index.tsx
pages/messaging.tsx
pages/subscription/whatsapp.tsx

Fixed description meta following #1200 - should have been using `name` instead of `property`

Fix description meta

---

.github/workflows/community-slackpost-repo-activity.yml
scripts/github_actions/communityActivitySlackPost.js

N/A
Created workflow to post OSS activity in Slack every 2 weeks or manually.
N/A
N/A

Actions: Created workflow to post OSS activity in Slack

---

messages/courses/de.json
messages/courses/es.json
messages/courses/fr.json
messages/courses/hi.json
messages/courses/pt.json

What changes did you make and why did you make them?
Updated language changes for rate this session

Updated translations for rate this session

---

package.json
yarn.lock

N/A
Updated cross-spawn to latest stable version.
Updated Slack GitHub Action to exclude chaynteam contributors. 

Deps: Update cross-spawn with resolution to latest stable version

---

components/storyblok/StoryblokCarousel.tsx
package.json
styles/globals.css
yarn.lock

N/A
Updated to new design on carousel
Yep!
I work for chayn

feat: update carousel to new design

---

.gitignore
components/forms/ApplyCodeForm.tsx
components/forms/RateSessionForm.tsx
components/forms/RegisterForm.tsx
components/forms/ResetPasswordForm.tsx
components/forms/WhatsappSubscribeForm.tsx
components/forms/WhatsappUnsubscribeForm.tsx
components/layout/Header.tsx
constants/common.ts
package.json
pages/account/disable-service-emails.tsx
utils/helper-types/translations.d.ts

fix: types for tests

---

components/storyblok/StoryblokCarousel.tsx

N/A
Updated the function that calculates the number of slides in a carousel
Yes

fix: carousel slide number

---

cypress.config.ts
cypress/integration/tests/cookie-consent.cy.tsx
cypress/integration/tests/initial-exploration.cy.tsx
cypress/integration/tests/reset-password.cy.tsx
cypress/integration/tests/therapy-usage.cy.tsx
cypress/integration/tests/user-disable-service-emails.cy.tsx

fix: memory issue cypress tests

---

messages/shared/de.json
messages/shared/es.json
messages/shared/fr.json
messages/shared/pt.json

fix: translate messages for related content

---

components/cards/ShortsCard.tsx
components/layout/NavigationMenu.tsx
components/layout/PartnerHeader.tsx
components/storyblok/StoryblokCard.tsx
components/storyblok/StoryblokRelatedContent.tsx
components/storyblok/StoryblokResourceConversationPage.tsx
components/storyblok/StoryblokResourceShortPage.tsx
components/storyblok/StoryblokSessionPage.tsx
hooks/useReferralPartner.ts

N/A
Fixing issues around related content being shown on the shorts page
Yes
Same tests failing as before

Partner content functionality

---

components/common/Carousel.tsx

N/A
Temp fix for carousel not sliding properly

fix: carousel make slide length a screen

---

messages/shared/fr.json

Update fr.json - montre to regarder

---

.babelrc
.github/workflows/build-and-test-prs.yml
.github/workflows/community-issue-comment.yml
components/head/GoogleTagManagerScript.tsx
pages/_app.tsx
pages/_document.tsx
styles/theme.ts

This is the first of several PRs to migrate next.js from pages to app router. This PR completes updating new features introduced in v13 that work with both pages and app router. See migration [guide steps](https://nextjs.org/docs/app/building-your-application/upgrading/app-router-migration#upgrading-new-features) 
Updates:
- uses new `next/font` import for font optimisation
- new `script` changes required

App migration: update new features 

---

components/storyblok/StoryblokSessionPage.tsx
utils/getChatAccess.ts

#1180 
Removed liveCourseAccess references from the getChatAccess function as well as the unnecessary parameters sent 
in StoryblokSessionPage.tsx
Fond the project in https://forgoodfirstissue.github.com/, looking forward to keep contributing :D

remove liveCourseAccess references

---

.github/workflows/cypress-release-test.yml
app/[locale]/action-handler/page.tsx
components/crisp/utils/createCrispProfileData.test.ts
components/forms/AboutYouDemographicForm.tsx
components/forms/RegisterForm.tsx
components/forms/ResetPasswordForm.tsx
components/guards/AuthGuard.tsx
components/layout/LanguageMenu.tsx
components/pages/RegisterPage.tsx
components/storyblok/StoryblokRelatedContent.tsx
components/storyblok/StoryblokWelcomePage.tsx
cypress/integration/tests/user-course-session-behaviour.cy.tsx
lib/utils/generateReturnQuery.ts

Test failure logs:
```
1) A logged in user should be able to navigate to a course session and complete it
Should read activity & bonus content, complete session and complete feedback form:
CypressError: `cy.visit()` failed trying to load:
https://bloom-frontend-7gkanwx2n-chaynhq.vercel.app/courses/healing-from-sexual-trauma/what-is-sexual-trauma
```

Fix course session behaviour test

---

components/guards/AuthGuard.tsx
components/layout/LanguageMenu.tsx
cypress/integration/tests/user-course-session-behaviour.cy.tsx

removed redirect navigation causing issues with language switching to `en`

Fix language menu

---

app/[locale]/courses/[slug]/[sessionSlug]/page.tsx
components/forms/ApplyCodeForm.tsx
components/layout/BaseLayout.tsx
components/layout/CookieConsent.tsx
components/pages/NotFound.tsx
components/session/SessionChat.tsx
styles/globals.css

Fixed all styles bugs following #1279 
The `globals.css` file was no longer applied, creating multiple styles issues across the app
Also improves cookie consent modal styles

App migration style fixes

---

app/[locale]/courses/[slug]/[sessionSlug]/page.tsx
components/cards/CourseCard.tsx
components/cards/SessionCard.tsx
components/cards/ShortsCard.tsx
components/guards/AuthGuard.tsx
components/pages/CoursesPage.tsx
components/session/SessionHeader.tsx
components/storyblok/StoryblokCoursePage.tsx
components/storyblok/StoryblokRelatedContent.tsx
components/storyblok/StoryblokResourceConversationPage.tsx
components/storyblok/StoryblokResourceShortPage.tsx
lib/utils/getDefaultFullSlug.ts

Resolves multiple issues on migration epic #1293 
Refactored storyblok `full_slug` logic to handle removing locales

Fix migration bugs

---

components/guards/SetupMFA.tsx
components/pages/LoginPage.tsx
lib/hooks/useLoadUser.ts

Adds logs for ongoing work on superadmin 2fa #1311

Superadmin multifactor add logs

---

app/[locale]/action-handler/page.tsx
components/forms/LoginForm.tsx
components/guards/SetupMFA.tsx
components/guards/VerifyMFA.tsx
lib/hooks/useLoadUser.ts

Iteration on #1311 to fix action-handler failing 500
Adds error logs for MFA

Superadmin multifactor auth error logs + await action handler

---

lib/auth.ts
lib/rollbar.ts

Fixes verify email confirmation function
Also fixes rollbar setting staging env as `production`

Fix verify email + rollbar env

---

components/guards/SetupMFA.tsx
components/guards/VerifyMFA.tsx
i18n/messages/auth/de.json
i18n/messages/auth/en.json
i18n/messages/auth/es.json
i18n/messages/auth/fr.json
i18n/messages/auth/hi.json
i18n/messages/auth/pt.json
lib/auth.ts

Continues work on superadmin MFA #1311 
Fixes verify 2FA function

Superadmin multifactor fix verify MFA + add helper text

---

components/guards/SetupMFA.tsx
components/guards/VerifyMFA.tsx
lib/auth.ts

Continues fixing #1311 issues following testing

Superadmin multifactor auth - fix verify methods

---

components/guards/AuthGuard.tsx

N/A
Add redirects on admin pages so there is no preview

Redirect admin pages

---

app/[locale]/action-handler/page.tsx
cypress/integration/tests/admin-dashboard.cy.tsx

Skips superadmin tests for now as struggling to get 2FA working in cypress - see #1317 . We'll aim to followup with fixing these tests.
Also adds error message for email verification error.

Superadmin multifactor fixes - skip tests

---

cypress/integration/after/after.cy.tsx
cypress/integration/tests/user-update-email.cy.tsx

Fixes test following redirect change in #1318

Fix user update email redirect test

---

app/[locale]/shorts/[slug]/page.tsx
components/storyblok/StoryblokResourceShortPage.tsx

N/A
- allowed related session to take a session or a course in either array or object format 
Yes

fix: related session field bug

---

.github/workflows/cypress-release-test.yml
.github/workflows/cypress-test.yml
package.json
yarn.lock

Deps: Upgrade dependabot alerts

---

components/storyblok/StoryblokSessionPage.tsx
lib/utils/hasAccessToPage.ts

N/A
Made pages render with a preview under the login overlay. 
Yes

fix: make preview available for session pages

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/community-issue-comment.yml
.github/workflows/dependabot-pr-review.yml

- dependabot-pr.review.yml: Upgrade dependabot PR review to also scan forks
- codeql-analysis: opt-in to public preview of actions language support
- community-issue-comment: fix if condition to post comment on stale workflow run completion
- dependabot.yml: auto assignees and reviewers
N/A
Improve efficiency of dependabot and codeql & fix stale issue comment bug
Before submitting, check that you have completed …

Actions: Upgrade scanning coverage and fix stale issue comment

---

app/[locale]/shorts/[slug]/page.tsx
components/resources/ResourceShortsHeader.tsx
components/storyblok/StoryblokResourceShortPage.tsx

NA
- refactor of how we add related session or courses to shorts

fix: wip solution to shorts related content being a course or a session

---

.github/workflows/build-and-test-prs.yml
.github/workflows/cypress-release-test.yml
.github/workflows/cypress-test.yml
components/crisp/CrispIframe.tsx
components/forms/LoginForm.tsx
docs/local-development.md
package.json

Upgrades node version to 22.x to stay in line with bloom-backend

Upgrade node v22

---

components/forms/LoginForm.tsx
components/pages/LoginPage.tsx

Fixes setup MFA bug introduced in #1380 where user was redirected to courses instead of MFA flow

Fix setup mfa flow

---

components/cards/ShortsCard.tsx
components/common/Carousel.tsx
components/pages/CoursesPage.tsx
styles/theme.ts

Carousel style has been updated, when hovering over the shorts a play icon with user-friendly animation appears, also added fade-out on the right side of the carousel.
Modified the ShortsCards, Carousel, CoursesPage components and added an IconButton.
Through opensourcefriday and decided that this is a perfect project for me as my first open source.
Before submitting, check that you have completed the following …

Upgrade carousel designs

---

components/pages/CoursesPage.tsx
components/session/SessionProgressDisplay.tsx
package.json
yarn.lock

N/A
Ensured useGetCourseUserQuery was skipped in all components when user is logged in. 
Yes

fix: unauthorised calls to courses-user

---

.github/configs/labeler.yml
.github/workflows/build-and-test-prs.yml
.github/workflows/codeql-analysis.yml
.github/workflows/community-issue-comment.yml
.github/workflows/community-slackpost-repo-activity.yml
.github/workflows/community-stale-management.yml
.github/workflows/dependabot-pr-review.yml
.github/workflows/scan-and-label-forks.yml

N/A
- .`github/configs/labeler.yml` - defines config for labeler
- `.github/workflows/build-and-test-prs.yml` - skip job if triggered by fork due to no access to secrets 
- `.github/workflows/codeql-analysis.yml` - enable codeql run on updated PRs
- `.github/workflows/dependabot-pr-review.yml` - run on pull_request and verify context in log
- `.github/workflows/scan-and-label-forks.yml` - configured new workflow to scan code changes in forked PRs and label when sensitive files are modified
- all changes to workflows starting with 'community' in the file name - cleaned up header docs
These changes were made to ensure workflows triggered by pull requests are running in the correct context, bypass jobs requiring secrets on forked PRs, and enhance security by adding a label to forked PRs to …

Actions: scan and label forked PRs 

---

.github/dependabot.yml
package.json
yarn.lock

N/A
Updated a few dependencies based on dependabot PRs.
Enabled dependabot PR grouping:
- minor updates and patches will be grouped by 2 categories: dev-dependencies & production dependencies
- major updates will be left ungrouped for review to isolate potential breaking changes.
Yes
After submitting, please be available for discussion. Thank …

Deps: Config dependabot grouping + updates

---

.github/configs/labeler.yml
.github/dependabot.yml
app/[locale]/courses/[slug]/[sessionSlug]/page.tsx
components/common/ResourceCarousel.tsx
components/pages/CoursesPage.tsx
components/storyblok/DynamicComponent.tsx
components/storyblok/StoryblokResourceCarousel.tsx
components/storyblok/StoryblokResourceConversationPage.tsx
cypress/integration/tests/user-course-session-behaviour.cy.tsx
lib/auth.ts
lib/store/coursesSlice.tsx
lib/store/resourcesSlice.tsx
lib/utils/filterStoryByLanguageAndPartnerAccess.test.ts
lib/utils/filterStoryByLanguageAndPartnerAccess.ts
lib/utils/richText.tsx
scripts/checkTranslation.js

N/A
- Created new resource carousel component
- Refactored course page to use new component
yes

feat: storyblok resource carousel + refactoring course page carousels

---

components/common/ResourceCarousel.tsx

Resource Carousel changes when user access changes so that we show the correct items in the carousel

fix: resource carousel refreshes when user access changes

---

app/[locale]/shorts/[slug]/page.tsx
components/common/ResourceCarousel.tsx
lib/utils/filterStoryByLanguageAndPartnerAccess.test.ts

Getting an error that is unclear and not reproducable locally. So making guesses as to what it might be. Heres sorting out how state works in the Resource carousel as setCarouselCourses might cause issues.

fix: separate out resource state in Resource Carousel

---

app/[locale]/page.tsx
components/common/ResourceCarousel.tsx
components/pages/CoursesPage.tsx
components/storyblok/StoryblokResourceCarousel.tsx
lib/storyblok.ts
package.json
yarn.lock

N/A
Fix initialisation issue in the resource carousel. The storyblokApi could not be called froma. client component. 
Yes

fix: resource carousel initialisation bug

---

app/[locale]/action-handler/page.tsx

N/A
Fixed password reset flow which was broken by passing query params wrong to the redirect function

fix: password reset flow

---

app/[locale]/welcome/[partnerName]/page.tsx
lib/utils/filterStoryByLanguageAndPartnerAccess.ts

N/A
Needed to resolve relations for resource_carousel in storyblok API and make the resource carousel less brittle.

fix: resource carousel languages error

---

i18n/messages/account/es.json

https://www.notion.so/chayn/Correct-spelling-on-button-in-Bloom-signup-flow-191b1101e64f8093afc5faeb3b01b3bb

Update es.json change Saltar a cursos

---

.github/workflows/cypress-release-test.yml
.github/workflows/cypress-test.yml
cypress/integration/tests/meet-the-team.cy.tsx

Fix cypress paraelisation

---

components/session/SessionVideo.tsx
components/storyblok/StoryblokSessionPage.tsx
i18n/messages/courses/de.json
i18n/messages/courses/en.json
i18n/messages/courses/es.json
i18n/messages/courses/fr.json
i18n/messages/courses/hi.json
i18n/messages/courses/pt.json

Adds "Back to course" button on the session pages. There was previously no button at the end of the page that navigates back to courses.

Session back button

---

components/storyblok/StoryblokSessionPage.tsx

Fast follow of #1446 as didnt merge the link href fix

Fix session back link 

---

components/forms/UpdatePartnerAdminForm.tsx
components/forms/UpdateTherapyAdminForm.tsx

Fixes params in line with changes to backend `getUsers` function

Fix getusers params

---

.github/workflows/cypress-release-test.yml
app/[locale]/therapy/book-session/BookTherapyPage.tsx
components/storyblok/StoryblokAccordion.tsx
components/storyblok/StoryblokTeamMemberCard.tsx
cypress/integration/tests/meet-the-team.cy.tsx
cypress/integration/tests/therapy-usage.cy.tsx
i18n/messages/therapy/de.json
i18n/messages/therapy/en.json
i18n/messages/therapy/es.json
i18n/messages/therapy/fr.json
i18n/messages/therapy/hi.json
i18n/messages/therapy/pt.json
package.json

Fixes tests for therapy redesign parent feature #1474

Therapy redesign - fix tests

---

i18n/messages/navigation/pt.json

Update pt.json Bate-papo

---

.github/workflows/cypress-release-test.yml
cypress.config.ts

N/A
1. cypress-release-test.yml: permissions added to resolve failure to fetch Vercel preview link job on workflows triggered by dependabot. See https://github.com/patrickedqvist/wait-for-vercel-preview/issues/56
2. cypress.config.json:  disables features in `cypress.config.json` that we no longer use and still add to runtime to increase e2e speed. See https://docs.cypress.io/app/references/configuration#Options

Refactor: optimize Cypress config for speed

---

i18n/messages/whatsapp/en.json

Updating Sign up to Subscribe to be consistent

Update en.json Notes from Bloom title

---

components/pages/CoursesPage.tsx

Adds promo to course page when logged out

feat: add logged out nfb promo on courses page

---

cypress/integration/tests/superadmin-mfa.cy.tsx
i18n/messages/auth/en.json

superadmin-mfa tests are failing due to updated copy strings in #1545 
This PR fixes test strings

Fix 2FA tests copy

---

i18n/messages/auth/de.json
i18n/messages/auth/en.json
i18n/messages/auth/es.json
i18n/messages/auth/fr.json
i18n/messages/auth/hi.json
i18n/messages/auth/pt.json

Adds missing string for wrong password error, used in the reauthenticate step in the MFA setup flow

Add missing wrong password string

---

components/cards/RelatedContentCard.tsx
components/common/Carousel.tsx
components/common/ResourceCarousel.tsx
components/storyblok/StoryblokCarousel.tsx
components/storyblok/StoryblokRelatedContent.tsx
components/storyblok/StoryblokResourceCarousel.tsx

This pull request refactors the carousel components to simplify their API, improve layout consistency, and enhance maintainability. The main change is the introduction of a new `CarouselItemContainer` component, which standardizes how carousel items are rendered and styled across different carousels. Several props and utility functions have been removed or replaced, and the code now avoids layout bugs related to slide width calculations. The changes affect multiple carousel usages throughout the codebase.
**Carousel Component Refactor and API Simplification**
* Introduced the new `CarouselItemContainer` component to wrap carousel items, replacing direct usage of `Box` and slide width calculations in all carousel implementations. This standardizes padding and width logic for carousel …

refactor: carousel component

---

components/storyblok/StoryblokTeamMemberCard.tsx

Fixes team member icons following #1562

Team member icon fixes 

---

components/resources/ResourceConversationHeader.tsx
components/storyblok/StoryblokResourceConversationPage.tsx
components/storyblok/StoryblokResourceSingleVideoPage.tsx
components/storyblok/StoryblokTeamMemberCard.tsx
styles/theme.ts

Improves cards styles globally

Improve cards styles

---

components/storyblok/StoryblokMeetTheTeamPage.tsx
components/storyblok/StoryblokTeamMemberCard.tsx

Fixes scroll to section action on team page

Fix team page scroll

---

components/cards/SessionCard.tsx
components/course/CourseIntroduction.tsx
components/layout/BaseLayout.tsx
components/layout/Header.tsx
components/layout/HomeHeader.tsx
components/pages/NotesPage.tsx
components/resources/ResourceConversationHeader.tsx
components/resources/ResourceShortsHeader.tsx
components/resources/ResourceSingleVideoHeader.tsx
components/session/SessionHeader.tsx
components/storyblok/StoryblokCoursePage.tsx
styles/common.ts
styles/theme.ts

Fixes styles for breadcrumb buttons positioning. The heading element is always in the same place now, by moving the breadcrumb buttons higher, closer to the nav. Mobile styles improved as some pages titles were being pushed down

Header + breadcrumb fixes
