chaynHQ/bloom-frontend

- .github/workflows/ci.yml
- Procfile
- package.json
[Ticket](https://www.notion.so/chayn/Setup-pilot-environment-deployment-d91182849a1248959ae81fa3c229c6b0)
This ticket includes setting up both frontend and backend app pipelines together, in a similar way.
Setup `bloom-frontend` and `bloom-backend` Heroku apps with one pilot environment for now.  Using heroku urls is okay for now, we'll set up a pilot subdomain for [chayn.co](http://chayn.co) later. Setup auto deployment with github, with a merge to `main` branch triggering a deployment to the pilot apps. Setup `dev` as the "base" branch in github.
Pipeline to mostly mirror YSM.
Add Github actions for linting and building as in YSM but keep lightweight for now.
Later when we're moving beyond pilot, we'll add a `pilot` branch (that auto deploys to the pilot apps) and new `staging` and …
> Setup pilot environment & deployment

- messages/therapyBooking/en.json
- pages/_app.tsx
- pages/therapy-booking.tsx
- pages/therapy-confirmation.tsx
- utils/authGuard.tsx
- utils/therapyAccessGuard.tsx
Adds therapy access guard to show an alternative view for users who try to access therapy pages, without having a Partner Access record or therapy access.
> Therapy access guard

- app/api.ts
- app/userSlice.tsx
- components/LoginForm.tsx
- components/RegisterForm.tsx
- components/TopBar.tsx
- components/UserMenu.tsx
- package.json
- pages/_app.tsx
- utils/authGuard.tsx
- utils/delay.tsx
- yarn.lock
Refactors AuthGuard and baseQuery to refresh the firebase user token if expired, and restore the user data again.
Handles app reloads and revisiting the app after e.g. a day.
The token passed to request headers is now loaded from state, not localstorage
> Keep user logged in + refresh tokens

- app/partnerAccessSlice.tsx
- app/userSlice.tsx
- package.json
Loadash import was causing a bug. 
`object.assign` works just as well
> Remove lodash

- components/CreateAccessCodeForm.tsx
- constants/enums.ts
- messages/partnerAdmin/en.json
Updating the `create-partner-access` page to include 3 options instead of 2, now that the courses and live chat are included in the platform.
> Update create partner access form

- components/CourseCard.tsx
- components/CourseIntroduction.tsx
- components/CreateAccessCodeForm.tsx
- components/Faqs.tsx
- components/Footer.tsx
- components/Header.tsx
- components/ImageTextGrid.tsx
- components/LoginForm.tsx
- components/RegisterForm.tsx
- components/ResetPasswordForm.tsx
- components/SessionCard.tsx
- components/VideoTranscriptModal.tsx
- pages/404.tsx
- pages/500.tsx
- pages/auth/login.tsx
- pages/auth/register.tsx
- pages/courses/[slug].tsx
- pages/courses/[slug]/[sessionSlug].tsx
- pages/courses/index.tsx
- pages/partner-admin/create-access-code.tsx
- pages/therapy/book-session.tsx
- pages/therapy/confirmed-session.tsx
- pages/welcome.tsx
- utils/partnerAdminGuard.tsx
- utils/therapyAccessGuard.tsx
The default for the MUI `<Typography>` component is `component="p" variant="body1"`. So we don't need to include these. This PR removes this unnecessary code throughout the codebase
> Refactor - remove unnecessary typography body1

- utils/richText.tsx
Richtext copy wasn't splitting into paragaphs because of typographys need to include `paragraph`.
> Fix richtext paragraph

- components/forms/LoginForm.tsx
- guards/authGuard.tsx
- utils/generateReturnQuery.ts
See https://www.notion.so/chayn/Redirect-after-login-f7442ca310d1450d8d79463d3cf6aba3 for ticket
- Note the choice of underscore was to avoid having to do router.query['return-url']. 
- Have dropped the requirement to do it after password reset as it adds alot of complexity
> Redirect to original url after authguard login

- components/layout/NavigationMenu.tsx
- next.config.js
- pages/action-handler.tsx
- pages/courses/[slug].tsx
- pages/courses/[slug]/[sessionSlug].tsx
- pages/courses/index.tsx
- pages/index.tsx
- pages/meet-the-team.tsx
- pages/welcome/[partnerName].tsx
Moved the public welcome in storyblok to the top level, as it was causing issues on `welcome/[partnerName]`
Multiple other fixes found whilst bug hunting - including including the language locale in the call to storyblok
> Build welcome fix

- components/layout/NavigationMenu.tsx
Currently, the "about" link shows information which is correct for public users but not bumble users. Since both types of users are shown this page, bumble users might find it confusing.
The temporary fix is to remove the "about" link.
> Remove "about" link from nav bar

- utils/generateReturnQuery.ts
Just a quick fix to cover the bug I created. I cannot use `router.pathname` to get the course slug. For now I am just going to redirect to courses but this can be improved.
> For course url, redirect to /courses in authguard

- components/forms/LoginForm.tsx
- components/forms/RegisterForm.tsx
- components/forms/ResetPasswordForm.tsx
Previously missed adding the field type to the `TextField` component for email fields.
> Add email field type

- app/coursesSlice.tsx
- app/partnerAccessSlice.tsx
- app/partnerAdminSlice.tsx
- app/userSlice.tsx
- components/forms/LoginForm.tsx
- components/forms/RegisterForm.tsx
- components/layout/NavigationMenu.tsx
- components/layout/UserMenu.tsx
- hooks/store.ts
Previously the state wasn't being cleared on logout. This wasn't easy to detect previously, as the menu wasn't in place, so just picked up on the bug. Before these changes, when logging out, the navigation menu remained as though you were logged in, because the state wasn't being cleared. 
This change clears the state by calling the `clearNameSlice` method on each slice individually, and removes the global `clearState()` function. This fixes the dispatch issue that was causing the bug, and also allows more control in the future to e.g. not clear one of the states like a new `browser` state that includes user preferences.
> Fix logout state

- components/forms/ResetPasswordForm.tsx
- You need to use the default Firebase email to get translations. We are doing this.
- We only use password reset email as far as I can tell so I only needed to change the language of that email.
- There are two ways of changing the language  `Firebase.auth().languageCode = “es”` or   the function `Firebase.auth().useDeviceLanguage().` This sets the current language to the default device/browser preference. I opted to go by Url to give a bit more choice to the user. But equally I could be wrong. Please update PR if this isn't the best method
> 190322-0749/ set password reset language

- README.md
- components/storyblok/DynamicComponent.tsx
- components/storyblok/Placeholder.tsx
- components/storyblok/StoryblokFaqs.tsx
- guards/authGuard.tsx
- pages/[slug].tsx
- pages/_app.tsx
- pages/courses/[slug].tsx
- pages/courses/[slug]/[sessionSlug].tsx
- pages/courses/index.tsx
- pages/index.tsx
- pages/meet-the-team.tsx
- pages/welcome/[partnerName].tsx
- Adds dynamic storyblok page (`pages/[slug].tsx`) and components (`DynamicComponent.tsx`), as described below
- Adds support for faq page - by adding it to the `publicPaths` list in `_app.tsx`
- Removes `cv` param as it was causing errors and i dont believe its required
As in readme:
**Dynamic pages**
Dynamic pages allow the team to create new content pages in Storyblok e.g. `/about-topic`, without requiring developer work*. Our top level dynamic route [[slug].tsx](pages/[slug].tsx) allows new pages to be added, with an infinite number of [StoryblokPageSection.tsx](components/storyblok/StoryblokPageSection.tsx) with nested components. [DynamicComponent.tsx](components/storyblok/DynamicComponent.tsx) can also be used to dynamically render components on a page, where the storyblok field is …
> Dynamic page + faq page

- components/layout/TopBar.tsx
- next.config.js
Adds back language menu to allow users to select language. 
Also sets `localeDetection` to `true`, taking the users browser locale as default, or falling back to `en` if we don't support their browser default.
> Show language menu + default browser  locale

- components/forms/WelcomeCodeForm.tsx
This missing `event.preventDefault()` was causing a redirect error from the register page, back to the welcome page.
> Fix welcome code form - missing event.preventDefault

- components/forms/ApplyCodeForm.tsx
- pages/courses/[slug].tsx
- pages/courses/[slug]/[sessionSlug].tsx
- utils/logEvent.ts
Firebase event params previously weren't loading params correctly, due to nested params not being supported by firebase/google analytics UI. Whilst its possible to make use of the nested params with big query, it's unlikely we'll implement this in the near future, so for now we're flattening the event params.
> Flatten firebase event params

- components/cards/TeamMemberCard.tsx
The teamMember.bio field is of type RichText and so needs to be rendered with RichTextOptions. It was previously being rendered as text.
> Make meet-the-team page live

- components/cards/TeamMemberCard.tsx
The teamMember.bio field is of type RichText and so needs to be rendered with
RichTextOptions.
> Fix team bio render

- components/cards/TeamMemberCard.tsx
- components/layout/NavigationMenu.tsx
- messages/navigation/en.json
- messages/navigation/es.json
Fixes image objectFit to `cover`
Before
After
Also adds the meet the team page to the navigation
> Meet the team added to nav + image fix

- pages/_app.tsx
This commit fixes bug which redirects users to the login page if they click on a reset password link in their email.
This bug occured because the redirect link from firebase was not identified by the app as pointing to a public page. Instead, an auth-guarded component was served which then triggered the app to show the login page.
Going deeper in the code, the issue occured because the mechanism to identify public paths did not work when the path contained query params. Since the reset-password email links did contain query params, it
was incorrectly classes as needing an auth guard.
The variables which hold the public paths and the current path have been renamed to contain 'head' as this makes it clear to the reader which part of the path is referred to in the code.
050422-1958 / Fix …
> Fix issue with password-reset flow

- components/layout/LanguageMenu.tsx
- components/layout/NavigationMenu.tsx
- components/layout/TopBar.tsx
- components/layout/UserMenu.tsx
Fixes spacing/flex issues on mobile, introduced when adding back the language menu
before
after
Also made the desktop nav a bit tighter, as it was overflowing at 900px
before
after
> Fix mobile topbar spacing

- components/layout/LanguageMenu.tsx
Currently when you language change, it gets the path name from router.pathname and sets the locale to the selected language. However, router.pathname uses variables like /courses/[slug] rather than courses/healing sexual trauma. Instead I have used, asPath to fix this issue.
> Use router.asPath not router.pathName for language change

- components/common/Faqs.tsx
- constants/faqs.ts
- messages/therapy/en.json
- messages/therapy/es.json
- messages/therapy/hi.json
Decisions:
- I've decided not to work on getting the link to look like a proper link at the moment as it was already fiddly. I think the fact that the information is up there is enough
- I've had to create a weird list thing in the faqs. I don't know how reusable this is but we might find a usecase for this in the future.
> Add limitation of liability to therapy faq

- utils/getAccountType.test.ts
- utils/getAccountType.ts
- utils/logEvent.ts
- add account meta data for tracking purposes
> Add account type to analytics meta data

- utils/getAccountType.test.ts
- utils/getAccountType.ts
I'm passing through partnerAdmin which is meaning everyone is a partner admin everywhere as I'm not checking if id is null  😱
> check partner admin id exists in GA events

- .gitignore
- components/storyblok/StoryblokRow.tsx
After upgrading Storyblok from V1 to V2 the column prop for
StoryblokRow has changed.
Previously, the StoryblokRow column prop was always an array.
However now the prop can be an array or an object.
To handle this lack of consistency in the prop type, this commit
wraps the column prop in an array if it is an object.
> 070922-1750 / Fix build fail

- .github/workflows/merge-pr-develop.yml
- .github/workflows/pull-request.yml
- cypress.config.ts
- cypress/integration/reset-password.cy.tsx
Dashes are not allowed but underscores are.
61d36d1c2f / Set up cypress run
> Update naming of cypress vars to match github secrets format

- .github/workflows/build-and-test-prs.yml
- .github/workflows/deploy-to-prod.yml
- .github/workflows/deploy-to-staging.yml
This allows deploys to be prevented by failing builds. The previous commit aiming to do the same did not work.
2d638a6cc1 / Restructure github actions
> Extract build-&-test action into deploy actions

- pages/courses/index.tsx
The FF_DISABLED_COURSES var is only available on the server side. With this change, the disabled courses are removed before the props are sent over to the front end.
3d3abfa9a6 / Enable courses in french
> Filter courses on Next server

- components/storyblok/DynamicComponent.tsx
- components/storyblok/StoryblokRow.tsx
- components/storyblok/StoryblokRowColumnBlock.tsx
- components/storyblok/StoryblokRowColumnBlok.tsx
- components/storyblok/StoryblokTypes.d.ts
- utils/richText.tsx
- This parallel component will allow us to support both the rich text StoryblokRow and the block only StoryblokRow
- This will allow a phased return back to the block only StoryblokRow. This will also allow Portugese pages in Storyblok to be set up correctly
> [FYI] New storyblok row component

- next.config.js
PWA is causing errors and this change is to prevent these errors. As this feature does not seem to be used significantly, it will be removed at a future date.
ee18f0711a / Disable PWA
> Disable PWA temporarily

- components/layout/Header.tsx
Currently descriptions are quite long and are continuous text. This will allow for better formatting with spaces.
The change in storyblok will happen after this is pushed to live.
> Update Header to use richtext for description

- components/forms/CreateAccessCodeForm.tsx
- constants/enums.ts
These two features will now be provided by automatic access codes. The only time admin generated codes are required is for therapy. The use of the `selectedTier` variable is still left in case we want to bring back multiple options in the future.
> [HIGH LEVEL] Automatic Partner Access: Remove chat and course options

- components/layout/NavigationMenu.tsx
- guards/authGuard.tsx
- pages/_app.tsx
- pages/auth/login.tsx
- fix issue where fresh reload of pages mean't a logged in user was redirected to login page and then courses
- tested that admin dashboard can be accessed via direct link
- tested that after logout the user cannot see the page 
- tested partner admin page can be accessed via direct link
- also adding here a change for a previous bug fix that Patricia did for us - the redirect for a logged in user away from the  login page. She did it correctly but when merging, I made a mistake and rebased to a previous version of her code. Just realised this when looking at the redirects for this bug.
> Fix admin redirect

- components/session/GridBonusContent.tsx
- components/session/MultipleBonusContent.tsx
- pages/courses/image-based-abuse/[sessionSlug].tsx
Changed the view of Bonus Content for Image Based Abuse course to display as a column rather than a grid. 
c25b293655 / IBA: Change bonus content layout from grid to column
> Remove grid bonus content

- package.json
- utils/richText.tsx
- yarn.lock
- update storyblok-renderer package to enable NODE_EMOJI resolver
- install gemoji to get Name to Emoji mapping 
- Storyblok sense us only the emoji name as a string and we have to map that to an emoji hence the installation of a mapping library
> [HIGH LEVEL] Enable emojis in richtext

- cypress/integration/auth-redirect.cy.tsx
- guards/authGuard.tsx
- added documentation
- removed check for firebase update applied as its not necessary and when a user is not logged in and lands on an authed page, this will never be true
> courses page  stuck on loading page when logged out

- app/userSlice.tsx
- cypress/integration/partner-admin.cy.tsx
- guards/authGuard.tsx
- pages/_app.tsx
- I think using user.loading across 2 requests leaves us exposed to bugs so I've created a firebaseTokenLoading state on the user
- user.token tells us the same thing as firebaseTokenApplied so removed the later
- Added Cypress test to ensure that admin dashboard redirect is working on log in
> Course loading bug take 2

- app/userSlice.tsx
- cypress/integration/auth-redirect.cy.tsx
- guards/authGuard.tsx
- guards/publicPageDataWrapper.tsx
- pages/_app.tsx
- utils/generateReturnQuery.ts
- I've tried to add better documentation of the auth guard although it might still be confusing.
- I've Added a onAuthStateChanged listener to both public page wrapper and auth guard in the aim to just keep auth contained to each for readibilities sake, although I am sacrificing duplication. I was looking at this[ implementation](https://blog.logrocket.com/implementing-authentication-in-next-js-with-firebase/) for inspiration. It is interesting that they use contexts. Perhaps this might be a better direction to go in the future
- Another thing I learnt is that children useEffects run before parent useEffects. Previously the checking for the token in app.tsx happened after the useEffects in the authguard ran, hence we experience the redirect issues. 
- I've set user.authStateLoading as …
> Auth session redirects bug

- cypress/integration/activities.cy.tsx
- cypress/integration/grounding-exercises.cy.tsx
- guards/authGuard.tsx
- guards/publicPageDataWrapper.tsx
- pages/auth/login.tsx
- Add cypress test timeouts to improve raciness 
- Fetch just audio component in grounding to allow for file changes on the content side 
- Sign out of firebase auth if callGetUser fails to avoid eternal redirects
> Fix Auth redirect bug when callGetUser fails and improve racy cypress tests 

- config/simplybook.ts
Paasing in the user id to the simply book widget so we can use it to link the user based on their id rather than their email address. This will need to be merged into develop so that it can be tested on staging with the zapier / simplybook integrations. May need code changes after testing!
> user id field added to the simply book widget config

- README.md
I have appended the following statement to the README below the header one, 'Bloom Frontend': 'To delve into a comprehensive exposition of this project's fundamental principles and structural framework, kindly peruse the contents of the /docs directory
> Address issue #624 link the /docs to README.md

- components/common/Link.tsx
- components/layout/Footer.tsx
- components/layout/Header.tsx
- components/layout/PartnerAdminHeader.tsx
- components/storyblok/StoryblokAudio.tsx
- components/storyblok/StoryblokVideo.tsx
- components/video/Video.tsx
- next-env.d.ts
- package.json
- pages/_app.tsx
- tsconfig.json
- yarn.lock
N/A as issue held in notion. We were having issues with bloom.chayn.co/de being redirected to bloom.chayn.co. So german users are seeing the English version of the side. Error below: 
`[Error: Invariant: attempted to hard navigate to the same URL /de https://bloom.chayn.co/de]`. This issue was fixed in Next 13.0.4 see [issue](https://github.com/vercel/next.js/issues/43088) 
- Update next 13.5.4. This meant I then had to subsequently update react 18.2, react-dom 18, react-player 2.13
- Came across 2 issues enroute which I have made changes to solve:
- React player issue https://github.com/cookpete/react-player/issues/1474 
- Material UI Link issue https://github.com/mui/material-ui/issues/34893
- to fix a redirect bug
> Update next 13.5.4, react 18.2, react-dom 18, react-player 2.13

- components/forms/UpdateTherapyAdminForm.tsx
In notion, N/A
- filter partner access codes by active so admins don't update inactive partner access codes
- fix bug where super admins acciddentaly could add therapy sessions to inactive access codes
> fix: stop superadmins updating inactive therapy codes

- styles/hotjarNPS.css
> NPS styles - more specific selectors 5

- components/forms/AboutYouDemographicForm.tsx
N/A - ticket in notion
- Changed when the required field runs in material UI as it is expecting a string in a textfield. 
- fix an issue in submitting about-you form as required autocomplete was failing.
> Gender multiple choice bug fix

- styles/hotjarNPS.css
> NPS styles - more specific selectors 7

- package.json
- yarn.lock
N/A
Downgraded to Nextjs because of 307 redirect issue on 3.4.19 and above.
Downgraded to Nextjs because of 307 redirect issue on 3.4.19 and above. See issue https://github.com/vercel/next.js/issues/55648. No progress so far.
> fix: language url bug fixed by downgrade to nextjs 13.4.19

- middleware.ts
- package.json
- yarn.lock
N/A
Using baseURL to create https redirect rather than the request headers. 
- Quick fix to try and get around next issue
> Middleware hack to get around issies in next 13.4.19 

- package.json
- pages/_app.tsx
- yarn.lock
Add [vercel analytics](https://vercel.com/docs/analytics). Currently doesn't use custom events and just stores basic activity
To test the vercel integrations and serve as an extra source of data primarly for developers, but also as a backup to google analytics
Note vercel analytics are [compliant with GDPR ](https://posthog.com/blog/best-gdpr-compliant-analytics-tools#6-vercel-web-analytics)
> Add vercel analytics

- README.md
Reconfigured README docs to include directions for external contributors.
These directions were removed with the latest upgrade to Vercel.
> Docs: Update README with env vars for external contributors

- next.config.js
Add patch/fix for PWA `bad-precaching-response` error - see [issue](https://github.com/shadowwalker/next-pwa/issues/288) and suggested [fix](https://github.com/shadowwalker/next-pwa/issues/288#issuecomment-953799577)
```
Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://bloom.chayn.co/_next/app-build-manifest.json","status":404}]
at Z.S (https://bloom.chayn.co/workbox-9b4d2a02.js:1:16900)
at async Z.U (https://bloom.chayn.co/workbox-9b4d2a02.js:1:16452)
at async Z.q (https://bloom.chayn.co/workbox-9b4d2a02.js:1:7597)
```
> Fix PWA with buildExcludes + runtimeCaching

- next.config.js
Add patch/fix for PWA bad-precaching-response error - see https://github.com/shadowwalker/next-pwa/issues/288 and suggested https://github.com/shadowwalker/next-pwa/issues/288#issuecomment-953799577
```
Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://bloom.chayn.co/_next/app-build-manifest.json","status":404}]
at Z.S (https://bloom.chayn.co/workbox-9b4d2a02.js:1:16900)
at async Z.U (https://bloom.chayn.co/workbox-9b4d2a02.js:1:16452)
at async Z.q (https://bloom.chayn.co/workbox-9b4d2a02.js:1:7597)
```
> Fix PWA with buildExcludes

- .github/workflows/create-release-pr.yml
Replaced cypress-run job on the `create-release-pr` action
This was removed in the previous migration to Vercel. Adding back now as realised it's the only place that tests are run (rather than being run on each branch)
> Replace cypress-run job

- .github/workflows/create-release-pr.yml
- .github/workflows/cypress-release-test.yml
- .github/workflows/cypress-test.yml
Delays running tests on main until the new preview/staging deployment is complete. Uses [wait-for-vercel-preview](https://github.com/patrickedqvist/wait-for-vercel-preview) action to prevent tests running until the preview app is redeployed.
The vercel deployment for preview (now https://bloom-frontend-git-develop-chaynhq.vercel.app/) would not have completed before the tests were run.
> Fix production testing workflow - run tests on main PRs

- .github/workflows/create-release-pr.yml
Fixes error on create-release-pr deps as the previous job was removed/moved to `cypress-release-tests`
> Fix dep on create-release-pr

- .github/workflows/cypress-release-test.yml
wait-for-vercel was [responding](https://github.com/chaynHQ/bloom-frontend/actions/runs/7046448434/job/19178267842?pr=725) with `Could not find any deployments for actor vercel[bot], retrying (attempt 1 / 30)` and timed out at 120 seconds before the deployment was ready
> Fix cypress-release-tests - increase timeout

- .github/workflows/cypress-release-test.yml
Downgrade wait-for-vercel-preview due to 401 error and [issue](https://github.com/patrickedqvist/wait-for-vercel-preview/issues/54) suggesting this isnt the case on 1.2.0
> Fix cypress-release-test - downgrade action

- .github/workflows/cypress-release-test.yml
Changed order of if statement on github action step, to prevent the step skipping too early.
> Fix cypress-release-tests - rearrange if

- .github/workflows/cypress-release-test.yml
Cypress release tests action is still not being triggered. Test using `github.ref == 'refs/heads/develop'` as the ref
> Fix cypress release tests - develop branch

- .github/workflows/cypress-release-test.yml
Reverting to original implementation to use the [wait-for-vercel-preview](https://github.com/patrickedqvist/wait-for-vercel-preview) action, as `deployment_status` can't filtering branches nicely to only run tests on `main` PRs.
Final solution only works now due to removing the protection on vercel preview branches, so no more 401 errors when trying to access the vercel deployments
> Final fix for cypress-release-tests - use wait-for-vercel-preview

- components/banner/SignUpBanner.tsx
- components/common/Column.tsx
- components/common/PageSection.tsx
- components/common/Row.tsx
- components/layout/AppBarSpacer.tsx
- components/layout/LeaveSiteButton.tsx
- components/storyblok/StoryblokPageSection.tsx
- components/storyblok/StoryblokRow.tsx
- components/storyblok/StoryblokRowColumnBlock.tsx
- constants/enums.ts
- cypress/integration/auth-redirect.cy.tsx
- cypress/integration/home.cy.tsx
- cypress/integration/initial-exploration.cy.tsx
- cypress/integration/navigation.cy.tsx
- guards/publicPageDataWrapper.tsx
- messages/shared/de.json
- messages/shared/en.json
- messages/shared/es.json
- messages/shared/fr.json
- messages/shared/hi.json
- messages/shared/pt.json
- pages/[slug].tsx
- pages/_app.tsx
- pages/chat.tsx
- pages/courses/index.tsx
- pages/subscription/whatsapp.tsx
- styles/theme.ts
N/A in notion
- refactor row and column and page section components
- create a banner for sign ups 
- Add banner to grounding, whatsapp, activities, courses and chat pages
To better expose our resources to users who are about to sign up
> feat: enable signup banner on partially public pages

- .github/workflows/build-and-test-prs.yml
- .github/workflows/cypress-test.yml
- .gitignore
- README.md
- components/crisp/CrispScript.tsx
- components/head/GoogleTagManagerScript.tsx
- components/head/HotjarScript.tsx
- guards/authGuard.tsx
- guards/publicPageDataWrapper.tsx
- package.json
- pages/_app.tsx
- pages/_document.tsx
- yarn.lock
- Adds [partytown](https://partytown.builder.io/) package to move third-party scripts (GTM + hotjar) to a web worker
- partytown requires node v18+, updated app to use node v20+ as this caused no errors
- partytown can't work with `react-hotjar` as we don't have access to the `<script>` element - this change removes the package in favour of the standard script. Note this also removes the functionality to add the user id to hotjar users - we should discuss if this is a feature we're willing to, or even favour removing. Hotjar is the top 1/2 most expensive scripts, up to 1s
Our third party scripts are blocking the main thread, and so blocking the page for 0.2-2+ seconds. Moving third-party scripts to a web worker, outside of the main thread, will massively increase performance.
- the …
> Add partytown to move scripts to web worker

- components/common/Column.tsx
- components/storyblok/StoryblokButton.tsx
- components/storyblok/StoryblokCard.tsx
- components/storyblok/StoryblokSpacer.tsx
- utils/richText.tsx
N/A - in notion
- enabled a slim style card
- added a small-medium width to columns
- size option on buttons
- spacer component to have custom spacing in UI
allow us to make a new style component on the home page
> Free service banner

- cypress/integration/activities.cy.tsx
N/A
Added a wait to ensure that auth checks are done before page content is checked 
- activities cypress test was blocking deployment
> fix: activities test failing due to to auth rerender

- .github/workflows/cypress-release-test.yml
- .github/workflows/lighthouse-performance.yml
Sets trigger for workflows on `push` instead of `pull_request`
Actions weren't being triggered consistently on `main` PRs
> Fix github actions on push 

- package.json
Removed unused packages `sharp` and `storyblok-editable`
As part of wider epic to improve Bloom performance, including reducing JS loaded/bundle size.
> Remove unused sharp and storyblok-editable deps

- components/storyblok/StoryblokAudio.tsx
- components/storyblok/StoryblokVideo.tsx
- components/video/Video.tsx
Swapped the `react-player` import from `/lazy` to `/youtube` (for video) or `/file` (for audio). 
As we're using next.js [dynamic lazy loading](https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#with-external-libraries) already, the lower bundle size should be a greater win than using the lazy loading in `react-player` however we can retest performance scores for this.
As part of a larger epic to improve Bloom performance, this reduces loaded JS/bundle size by ensuring only the youtube player module is loaded, instead of all available players (vimeo, soundcloud etc)
Reduces bundle size of `react-player` by 44%
**Before**
**After**
> Improve react player performance

- cypress/support/commands.js
Removed reference to undefined var, causing all tests to fail on setup
Left over bug from previous commits on firebase update #747
> Fix cypress firebase command

- components/common/Column.tsx
- components/common/Row.tsx
- components/storyblok/StoryblokCard.tsx
- components/storyblok/StoryblokCarousel.tsx
- components/storyblok/StoryblokRowColumnBlock.tsx
N/A part of homepage redesign. 
- enabled columns and rows to have extra horiztonal alighments and widths to fit with new design
Enable these designs
> feat: enable rows in carousels and add options to row/column

- lighthouse_desktop_budget.json
Increase lighthouse `total-blocking-time` budget value as it was quite low at 800ms and sometimes failing on CI
> Increase total-blocking-time

- .github/workflows/lighthouse-performance.yml
Lighthouse CI action is uploading artifacts for mobile only, presumably because only one set of artifacts can be uploaded (or a dir name clash) and the mobile job was run first. As desktop is the primary indicator, swapping artifacts to use desktop instead of mobile.
> Swap lighthouse jobs order

- components/common/Row.tsx
- components/storyblok/StoryblokCard.tsx
- components/storyblok/StoryblokCarousel.tsx
N/A
- Enabled dropdown option on cards
- When carousel slides = slides to show. The carousel disappears
- enable new desktop designs
> Theme cards

- .github/workflows/build-and-test-prs.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/cypress-release-test.yml
- .github/workflows/lighthouse-performance.yml
Fixed the workflow triggers (e.g.` on: push: branches: [develop]`) so that actions are also run on `push` and not just `pull_request`. The `push` to `develop` trigger is required for the first commit from `develop` -> `main` 
The following actions weren't being run on the initial commit on `develop` -> `main` PRs:
- cypress release tests
- build and test
See #797 for example of the first commit actions not including `cypress release tests` and `build and test` on the initial commit. From the second commit, those actions were run.
> Fix Github workflow triggers

- cypress/support/index.js
Replaces and fixes function to delete cypress users after cypress tests run
This was previously removed due to errors and too many cypress users existing in the db - they have now been cleared out and this function should safely run
> Replace delete cypress users function

- cypress.config.ts
- cypress/integration/_beforeAll.cy.tsx
- cypress/support/index.js
Created a new test suite `_beforeAll` to run the _before all_ function that deletes cypress test users.
The _before_ functionality was previously stored in `/cypress/support/index` and ran before/after every test suite, so 16 times. We just want this cleanup function to run once, instead of for each test suite.
To speed up tests and prevent 429 Too Many Requests errors, if we call this iterative cleanup function 16 times
> Run cypress before all only once

- components/banner/SignUpBanner.tsx
- pages/_app.tsx
- pages/index.tsx
Added functionality to store the referring partner for a user, to handle the case of a user entering via a promo url `/welcome/bumble` but then exploring the app and possibly signing up as a public user by navigating to `/register` instead of `/register?partner=bumble`. 
The `partnerReferral` value is stored in local storage so it's persisted, i.e. a user can leave the site and return later and we'll still know they originally reached Bloom via a partner referral link. This local storage is then read and applied to register urls
> Redirect unauthenticated user to partner register page

- newrelic.js
Updates default location of New Relic log file path to `/tmp` instead of `/var/task` which is read-only on vercel build
The default file path was causing the error below
```
New Relic failed to open log file /var/task/newrelic_agent.log
[Error: EROFS: read-only file system, open '/var/task/newrelic_agent.log'] {
errno: -30,
code: 'EROFS',
syscall: 'open',
path: '/var/task/newrelic_agent.log'
}
```
> Fix New Relic file path

- .gitignore
- newrelic.js
- pages/_document.tsx
Reverted New Relic logging filename to the default, enabled browser monitoring setting
New Relic monitoring is not currently working
> New Relic browser_monitoring + filepath update

- config/simplybook.ts
Renamed the simplybook custom field for user ID, as it's now named `data_field_1` on both environments. Presumably simplybook made a change here or we were using a different id for this simplybook [intake form field](https://help.simplybook.me/index.php/Intake_Forms_custom_feature)
The field name was disconnected on zapier due to renamed field, meaning the `client_id` (now `user_id`) zapier -> backend webhook was not being populated
> Fix simplybook user_id custom field

- components/storyblok/StoryblokCard.tsx
N/A
-  updated where we got the url from in storyblok so we could enable internal URLs to be used by storyblok. 
Clickable cards were not accepting internal url data from storyblok
> fix: enable clickable internal urls from storyblok

- components/layout/Header.tsx
Fixed position of cta in header - the cta container is now within the left text container, instead of in the root of the row flex
Recent changes moved the "start a chat" button on the chat page to be on the right instead of below the text - see screenshots
Before:
After:
> Fix header CTA position

- messages/auth/de.json
- messages/auth/en.json
- messages/auth/es.json
- messages/auth/fr.json
- messages/auth/hi.json
- messages/auth/pt.json
- pages/auth/register.tsx
Removed "More about how bloom works" link from the partner register pages
When we first designed Bloom we had access codes and more need to include this link. Now it's not as required so we're moving it for a more focussed flow
> Remove more about bloom link from partner register page

- .github/workflows/cypress-release-test.yml
- .github/workflows/cypress-test.yml
- components/forms/AboutYouDemographicForm.tsx
- components/forms/RegisterForm.tsx
- constants/gender.ts
- messages/account/de.json
- messages/account/en.json
- messages/account/es.json
- messages/account/fr.json
- messages/account/hi.json
- messages/account/pt.json
Responses from the demographics `/account/about-you` form are sent to google sheets. Users can select predefined options for gender, and/or use free text. The existing `gender` column is sent to google sheets as unserialised/unprocessed, which is valuable and will remain unchanged, but we're also adding new columns here for easier data processing.
This PR adds two new columns, `gender_options` and `gender_free_text`, so we have:
- selected options + free text (raw input) in users language, the existing `gender` field
- selected options only (no free text) in english, new `gender_options` field
- free text input in users language, new `gender_free_text`
To make gender data processing easier, e.g. by translating and formatting selected gender options, vs having to filter in multiple …
> feat: improved demographics gender sheets data

- next.config.js
n/a
we are retiring our about-our-courses page so have added the redirect 
To ensure that users don't land on a 404
Yes
> feat: redirect about our courses to courses page

- components/layout/LanguageMenu.tsx
Made Language Menu should disappear when a user selects a language
> Fix: Language Menu should disappear when a user selects a language

- app/partnerAdminSlice.tsx
- guards/partnerAdminGuard.tsx
Relates #917
- Update the `PartnerAdmin` interface and initial store state to represent the `active` property
- Update the `partnerAdminGuard` to reject where `active` status is not `true`
- The changes are necessary for satisfying requirements in issue #917 
- The store state and type system must be able to represent the new `active` property
- The auth guard must be able to check against this property
- Unit tests are all passing
- Cypress e2e has numerous failing tests locally mainly due do unavailable environment variables from what I can see...
- …
> Haydnba: Update partner admin authguard

- components/head/OpenGraphMetadata.tsx
N/A
I updated the url of the image url in the OpenGraphMetadata 
The url for the open graph image was incorrect so the social preview was broken.
> fix: change url for bloom_social_preview

- CONTRIBUTING.md
line 138, word "sustainable"
#936
fixed the typo in the contributing file, line n 138, word "sustainable"
the word was misspelled and correction was required
Yes
- Directions for running tests are in the README.md
> Typo in CONTRIBUTING file fixed

- .github/workflows/cypress-release-test.yml
- .github/workflows/cypress-test.yml
Added new `public_name` cypress variables to CI, added in #900
> Fix cypress CI missing public_name

- components/layout/NavigationDrawer.tsx
- components/layout/PrimaryNavigationDrawerLinks.tsx
Fixed nav bar colours being set to white due to new change in `globals.css` `color: inherit !important`
Before:
After:
> Fix nav links colours

- .github/workflows/cypress-release-test.yml
- components/layout/PrimaryNavigationDrawerLinks.tsx
- components/layout/SecondaryNavigationDrawerLinks.tsx
- components/layout/TopBar.tsx
- components/storyblok/StoryblokPage.tsx
- components/storyblok/StoryblokWelcomePage.tsx
- cypress/integration/user-account-settings.cy.tsx
- pages/404.tsx
- pages/500.tsx
- pages/auth/login.tsx
- pages/chat.tsx
- pages/courses/index.tsx
- pages/index.tsx
- pages/subscription/whatsapp.tsx
Refactor use of userToken state to userId. The user `id` is set after the user database record is set in state, but listening to `userToken` will create a race condition becuse there is a delay between token being set (login) and retrieving the user profile. Fixes partner admin redirect test
> Fix auth tests: refactor userToken -> userId

- components/head/OpenGraphMetadata.tsx
- guards/AuthGuard.tsx
- hooks/useLoadUser.ts
Added error handling for the case of the user record (GET /user/me) returning a success response with an invalid format (not having a `user.id`)
Improved `AuthGuard` redirect to prevent app from looping between auth/login pages, when the user flow doesn't complete
We had an incident on 3rd/4th July where the app was crashing due to:
- a backend change to the GET user response resulted in the user response being invalid - returning a `UserEntity` typed object instead of `GetUserDto`. The issue was introduced in [#505](https://github.com/chaynHQ/bloom-backend/pull/505) and fixed in [#511](https://github.com/chaynHQ/bloom-backend/pull/511)
- the frontend `useLoadUser` and `AuthGuard` had no catch to handle this response, i.e. a 200 success response with an invalid response type.
- this …
> Catch invalid user response crash

- package.json
- yarn.lock
Minor nextjs upgrade from 13.4.19 -> 13.5.1
Fixes this intermittent failing test issue
`Failed to execute 'measure' on 'Performance': The mark 'beforeRender' does not exist.`
> Upgrade next to 13.5.1

- .github/workflows/dependabot-pr-review.yml
Updated the dependabot vulnerability blocking setting from `moderate` to `high` 
All builds were failing due to required updates. Once we've updated our deps we could update the severity setting back to `moderate`
> Set dependabot blocking to high severity only

- cypress/integration/user-account-settings.cy.tsx
Fixes account settings test `Should have email reminder frequency form and load user data`
The test was previously expecting the `emailRemindersFrequency` input to start with 'Never' value checked, however this value could be changed by other tests and/or user activity on our staging site. 
The test now doesn't check the initial input and instead tests changing the input and the page maintaining the new input
> Fix account settings test

- .github/workflows/cypress-release-test.yml
- cypress/integration/user-account-settings.cy.tsx
Fixes account settings test `Should have email reminder frequency form and load user data`
Resets the email frequency setting to `never` so that the submit button is not disabled next time the test runs
Yes
> Fix user settings tests

- next.config.js
- pages/_app.tsx
#987 
Followed the potential solutions from this [thread ](https://github.com/mui/material-ui/issues/30410) and found the solution that seemed to work.
To enable server side rendering of the css to better handle the initial render
> Set emotion to true in compiler settings for next config

- components/layout/Footer.tsx
- cypress/integration/tests/delete-user.cy.tsx
- cypress/integration/tests/user-course-session-behaviour.cy.tsx
- hooks/store.ts
- pages/_app.tsx
- pages/courses/index.tsx
- utils/strings.ts
Fixed bug around referralPartner localstorage string (`e.g. bumble?code=123`) 
When this variable is set in storage, extra params are now split so that `bumble?code=123` becomes `bumble`
When `referralPartner` was set in localstorage, 0 courses were being loaded on the courses page, due to `bumble?code=123` not being split.
> Fix referral partner courses bug

- components/storyblok/StoryblokTeamMemberCard.tsx
- cypress/fixtures/meet-the-team.json
- cypress/integration/meet-the-team.cy.tsx
- cypress/support/commands.js
- cypress/support/index.d.ts
#1089
Created meet-the-team e2e test for english version
Yes
> Meet the team e2e test

- components/cards/SessionCard.tsx
- components/storyblok/StoryblokCoursePage.tsx
- guards/AuthGuard.tsx
- pages/courses/[slug].tsx
- pages/courses/image-based-abuse-and-rebuilding-ourselves/index.tsx
- pages/courses/index.tsx
#920
1. Make course cards on `/courses` page clickable, linking to `/courses/:slug`.
2. Ensure `/courses/:slug` pages are accessible pre-login.
3. Verify course sessions on `/courses/:slug` are non-clickable pre-login, clickable post-login.
4. Add signup CTA banner before the footer on `/courses/:slug`.
To make course content accessible pre-login.
yes
> feat: made course content available pre login

- cypress/fixtures/meet-the-team.json
N/A
Fixed broken meet the team cypress test that was based on content no longer there
To get tests to pass
yes
> fix: meet-the-team cypress test

- cypress/integration/tests/create-access-code.badoo.cy.tsx
#1089
Created partner admin - create access code e2e tests for badoo partner and english version
Yes
> Create access code e2e tests

- components/forms/CreatePartnerAdminForm.tsx
- components/forms/UpdatePartnerAdminForm.tsx
- cypress/integration/tests/admin-dashboard.cy.tsx
#1089 
Created admin dashboard e2e test for english version
Yes
> Admin e2e test

- cypress/integration/tests/500.cy.tsx
- pages/500.tsx
#1089
Created 500 e2e test for english version
Yes
> 500 e2e tests

- cypress/integration/tests/user-chat.cy.tsx
#1089
Added a very simple chat e2e test, to keep it flexible, for english version
Yes
> Chat e2e test

- cypress/integration/tests/action-handler.cy.tsx
#1089
Created action handler e2e test
Yes
NOTE: 404 tests are currently skipped at the moment due to an issue in the dev server until it is solved. Please skip this one as well if it is also failing in the dev server.
> Action handler e2e tests

- cypress/integration/tests/activities.cy.tsx
- cypress/integration/tests/grounding-exercises.cy.tsx
- cypress/integration/tests/navigation.cy.tsx
- cypress/integration/tests/notes.cy.tsx
- cypress/integration/tests/user-chat.cy.tsx
- cypress/integration/tests/welcome.badoo.cy.tsx
- cypress/integration/tests/welcome.cy.tsx
N/A
Made cypress tests create a user instead of reusing a user where possible. This is because logging in constantly with the same user was causing cypress tests to fail as firebase was returning the error auth/too-many-requests
To improve test raceyness
Yes!
> fix: avoid using public user where possible to improve flakiness

- components/common/Quote.tsx
- components/storyblok/StoryblokQuote.tsx
Improved the styling of the quote block, by moving the quote mark to the side instead of above the text.
Also slighting increased the image size and padding, and slightly reduced the text sizes and line heights.
Styling improvements flagged by Nadine
> Improve quote block styles

- cypress/integration/tests/home.cy.tsx
Updated an expected image alt and name, for the home testomonies test.
The test was breaking due to the image being replaced on storyblok
Yes
> Fix home illustration alt test

- cypress/integration/tests/register-partner-with-code.cy.tsx
- cypress/integration/tests/register-partner-without-code.cy.tsx
- cypress/integration/tests/welcome.badoo.cy.tsx
Fixed partner welcome page tests after #1134 
Tests breaking following content changes
Yes
> Fix partner welcome tests

- components/banner/SignUpBanner.tsx
- components/cards/SessionCard.tsx
- components/storyblok/StoryblokCoursePage.tsx
- pages/courses/image-based-abuse-and-rebuilding-ourselves/index.tsx
#1108 
Added functionality to ensure that if a user is not logged in, and clicks a session card on a course page (e.g. https://bloom.chayn.co/courses/recovering-from-toxic-and-abusive-relationships), the sign up banner is scrolled into view.
Previously, clicking a session card would result in no action, the card wasn't clickable. This scroll-to is better UX, leading the user to sign up to access a session
> Session card scroll to sign up

- components/cards/SessionCard.tsx
- cypress/integration/tests/welcome.badoo.cy.tsx
Fixed tests following content changes and logic in #1137 
Yes
> Fix badoo tests

- pages/[slug].tsx
- pages/_app.tsx
- pages/courses/[slug].tsx
- pages/courses/[slug]/[sessionSlug].tsx
- pages/courses/image-based-abuse-and-rebuilding-ourselves/[sessionSlug].tsx
- pages/welcome/[partnerName].tsx
- utils/getStoryblokPageProps.ts
Fixed `getStaticPaths` functions to ensure only storyblok pages that have been published, are added to the static paths list.
When building the app, there were many 404 errors for fetching storyblok data for pages. The errors were diluting the logging for builds - it's now easier to see the relevant issues from build logs
> Fix build paths

- cypress/integration/tests/user-messaging.cy.tsx
Fixes failing user messaging test following the heading string being updated in storyblok by the team.
Yes see below
> Fix user messaging test string

- components/head/DefaultHeadMetadata.tsx
- components/storyblok/StoryblokCoursePage.tsx
- components/storyblok/StoryblokMeetTheTeamPage.tsx
- components/storyblok/StoryblokPage.tsx
- components/storyblok/StoryblokSessionPage.tsx
- components/storyblok/StoryblokWelcomePage.tsx
- pages/index.tsx
- pages/messaging.tsx
- pages/subscription/whatsapp.tsx
Adds base `description` meta tag following #1185  to improve SEO. 
Previously thought `og:description` was the required meta, but both are required.
> Add description meta for SEO

- components/cards/CourseCard.tsx
- pages/courses/index.tsx
#1176
Removing live course access concept because there is no more support for live courses
I failed to run tests. I'm using a slightly older machine and  the cypress tools could not run successfully on my computer
GitHub
> Removing live course access concept

- .github/workflows/community-slackpost-repo-activity.yml
- components/banner/SignUpBanner.tsx
- components/banner/UserResearchBanner.tsx
- components/cards/CourseCard.tsx
- components/layout/Consent.tsx
- components/layout/Footer.tsx
- components/storyblok/StoryblokCoursePage.tsx
- hooks/store.ts
- hooks/useReferralPartner.ts
- pages/courses/index.tsx
- pages/index.tsx
- store/userSlice.tsx
Adds `cookiesAccepted` state property to `userSlice`. This can now be used to determine whether to set cookies, as required in upcoming task #1207 
Also refactors existing use of cookies to ensure all cookies use the `Cookies` package instead of `window.localStorage.setItem`
> Add cookiesAccepted state + refactor set cookies

- components/crisp/CrispIframe.tsx
Added crisp event `widget:loaded` which triggers our AI automations -> chatbox triggers. The chatbox trigger is responsible for sending/replacing the first crisp message with a translated one
> Add crisp event trigger

- .github/workflows/cypress-release-test.yml
> set cypress node version to 20

- components/storyblok/StoryblokRelatedContent.tsx
- messages/resources/fr.json
- messages/shared/fr.json
- pages/courses/index.tsx
N/A
Fix french text on shorts pages
Related Content should show courses by default if they haven't been tagged
> fix shorts french messages and related content

- components/cards/CourseCard.tsx
Minor design update to use the course images with a background instead of the primary image without a background.
> Fix course image background

- components/crisp/CrispIframe.tsx
Fixes issue with crisp not sending email to widget correctly, resulting in the user account not being connected to the chat in our crisp UI. 
The `[email]` was causing an issue although that's the formatting in the crisp [docs](https://docs.crisp.chat/guides/chatbox-sdks/web-sdk/dollar-crisp/#change-user-email)
> Fix crisp email connection

- app/[locale]/courses/[slug]/[sessionSlug]/page.tsx
- components/forms/EmailSettingsForm.tsx
- components/guards/AuthGuard.tsx
- components/layout/LanguageMenu.tsx
- components/pages/ErrorPage.tsx
- components/session/SessionCompleteButton.tsx
- components/storyblok/StoryblokVideo.tsx
- components/video/Video.tsx
- cypress/fixtures/subscription-whatsapp.json
Resolves the following issues related to app router migration #1279 
- fixes session pages not being statically generated due to paths missing `sessionSlug` param, causing 404s on staging
- fixes email settings form state
- fixes video config param error
> App migration fixes - session paths 404, email settings

- app/[locale]/shorts/[slug]/page.tsx
- components/course/CourseHeader.tsx
- components/layout/Header.tsx
- components/layout/HomeHeader.tsx
- components/layout/PartnerHeader.tsx
- components/pages/CoursesPage.tsx
- components/resources/ResourceConversationHeader.tsx
- components/resources/ResourceShortsHeader.tsx
- components/session/SessionHeader.tsx
- components/storyblok/StoryblokAccordion.tsx
- components/storyblok/StoryblokRelatedContent.tsx
- components/storyblok/StoryblokResourceConversationPage.tsx
- components/storyblok/StoryblokResourceShortPage.tsx
- i18n/messages/resources/de.json
- i18n/messages/resources/en.json
- i18n/messages/resources/es.json
- i18n/messages/resources/fr.json
- i18n/messages/resources/hi.json
- i18n/messages/resources/pt.json
- styles/common.ts
- Adds a "Back to conversations" and "Back to shorts" button to resource pages - scrolls to relevant list section on courses 
- Fixes session breadcrumb buttons that were previously only displaying "course" -> "overview" and not being translated. is now translated and shows the course name instead of "overview"
- prevents related content exercises and activities being shown for german, as the pages are not translated
- removes use of user research banner
> Fix breadcrumb buttons, prevent german activity related content, rm user research banner

- cypress/integration/after/after.cy.tsx
Skips the cleanup cypress users test, as superadmin access is broken in cypress for now - see #1317
> Skip after cypress cleanup

- app/[locale]/shorts/[slug]/page.tsx
- components/storyblok/StoryblokResourceShortPage.tsx
- components/storyblok/StoryblokSessionPage.tsx
- lib/storyblok.ts
- lib/utils/hasAccessToPage.test.ts
- lib/utils/hasAccessToPage.ts
Improved `hasAccessToPage` functionality whilst debugging an access issue (this was due to storyblok data in the end)
Fixed `shorts.related_session` to allow only one session object (previously allowed multiple and course objects) to avoid bugs if a course or multiple sessions is set instead
> Improve access to page function and shorts related session

- components/pages/LoginPage.tsx
- components/pages/RegisterPage.tsx
N/A
- New login link on create account page
Yup
> feat: login link on create account page, centre align login header

- cypress/integration/tests/user-update-email.cy.tsx
- next.config.js
N/A
Results from a PEN test showed that we didn't have enough security headers on our frontend app. This PR includes:
- content security policy
- X-Content-Type-Options
- Referrer-Policy
- Strict-Transport-Security
> Run cypress tests/security headers

- components/cards/CourseCard.tsx
- Set a uniform height for all course cards on the '/courses' page to address UI inconsistencies caused by varying title lengths.
- Implement responsive design adjustments to maintain consistent card heights across different devices (mobile, browser, tablet, etc).
- Verified that the course card heights remain uniform and responsive on various screen sizes.
Yes
https://forgoodfirstissue.github.com/
Before …
> fix: Ensure consistent course card heights on '/courses' page

- next.config.js
Fixes intl/locale redirects leading to 404. 
The issue was next-intl routing was not being applied to the `next.config.js` redirects, so we need to add additional locale matchers for redirects
> Fix intl redirects

- components/storyblok/StoryblokAccordion.tsx
Made several improvements to the accordion component in the messaging page:
1. Set accordions to be closed by default to improve initial page load experience
2. Removed unwanted spacing that appeared between accordions when opened
3. Added subtle background color (rgba(0, 0, 0, 0.09)) to accordion content for better visual distinction
These changes improve the user experience by:
- Reducing cognitive load on initial page load
- Creating better visual hierarchy between header and content
- Maintaining consistent spacing between elements
- Improving overall readability
I found you through For Good First Issue (https://forgoodfirstissue.github.com/).
> fix: Improve accordion styling and default state

- cypress/integration/tests/home.cy.tsx
N/A
Cypress tests are fialing because of spelling change. Decided that they shouldn't be so strict so have removed some of the tets
> fix: home cypress tests

- .github/workflows/cypress-release-test.yml
Currently, Cypress parallelization is non-functional in the GHA environment due to Cypress Cloud free tier limits.
Since we have decided to move forward without purchasing the paid tier, parallelization is being removed.
Removes parallelization from `cypress-release-test.yml`, keeping parallelization on `cypress-test.yml` for reference as its mainly run by staff. When the paid tier is purchased, parallelization will work as it is with dynamic distribution.
See internal notes for more information & links.
> Actions: Remove Cypress parallelization from cypress-release-test.yml

- lib/hooks/usePWA.test.ts
- lib/hooks/usePwa.ts
I used the logEvent method to add the events to GA4. 
I changed the local variable PWA_DISMISSED to PWA_BANNER_DISMISSED (this was the one used to set the cookie). This way I could use the PWA_DISMISSED and PWA_INSTALLED from /constants/events.
created a memoized function getPwaMetaData in usePwa.ts that extracts **browser** and **platform** from **navigator.userAgent**. Another alternative was to add this somewhere in the **lib/utils/pwaDetection**. I can do that upon request. 
Added mock functions for the test file for sending events to vercel and GA4
Yes, they ran
Steps to check and troubleshoot this in GA4:-
- First navigate to the "Debug View" by clicking on 
Settings (Gear Icon) -> Data-Display -> Debug View
- while debugView is open, run localhost on your browser and ensure that …
> added GA4 detection of events PWA_DISMISSED and PWA_INSTALLED

- next.config.js
Replace images.domains with images.remotePatterns in next.config.js.
> refactor: replace deprecated images.domains with images.remotePatterns

- cypress/integration/tests/conversations.cy.tsx
I created a new test file in cypress/integration/tests called conversations.cy.tsx. It's an end-to-end Cypress test for the Conversations features to ensure users can navigate to Courses, select a conversation, log in, play audio, and submit feedback.
This test passed all user flows for Conversations except the feedback form part. I got the error is that the feedback form doesn't appear after the user plays a conversation in the test, so I'm unable to test if the user can fill out the feedback form.
> Add Cypress integration test for new Conversations feature

- cypress/integration/tests/partner-content-access.cy.tsx
I made the new file partner-content-access.cy.tsx 
Before each block, the command cleanUpTestState() is run
It has 2 it blocks
Block - 1. Registers a Bumble user. Once the user is logged in, the browser navigates to /courses and asserts the existence of the specific course "Dating, boundaries, and Relationships" on the page
Block -2. Registers a regular user and navigates to /courses and asserts that the above course does NOT exist.
After each block cypress logs out.
Currently there's nothing "Badoo" specific that I found. Happy to add another it block with the exact same test for Badoo on request. (or something else)
Yes they ran
> added Cypress test to ensure partner users exclusively see partner-specific requests

- app/[locale]/therapy/book-session/BookTherapyPage.tsx
- lib/utils/richText.tsx
Fixes issue with richtext links not rendering on the therapy page, due to paragraph content being replaced in `replacePartnerName` function
> Fix therapy richtext link

- components/common/Carousel.tsx
- components/common/ResourceCarousel.tsx
- components/pages/CoursesPage.tsx
- components/storyblok/StoryblokCarousel.tsx
This pull request introduces updates to the `Carousel` component and its related implementations, focusing on improving customization, fixing layout issues, and cleaning up unused code. Key changes include the addition of a theme property for better styling flexibility, adjustments to slide width calculations, and the removal of unnecessary components and dependencies.
* Added a `carouselTheme` prop to the `CustomDots` component and a `theme` prop to the `Carousel` component to allow for primary or secondary theme customization. Updated the background color logic in `CustomDots` to reflect the selected theme. (`[[1]](diffhunk://#diff-3c40c606598b0bcbf1d19e82de166ea6292030ea712eec4cb138570acc6c752dR27-R50)`, `[[2]](diffhunk://#diff-3c40c606598b0bcbf1d19e82de166ea6292030ea712eec4cb138570acc6 …
> fix: carousel tidy

- .github/workflows/cypress-release-test.yml
N/A
See internal docs
This pull request includes a small change to the `.github/workflows/cypress-release-test.yml` file. The change removes the `permissions` block from the `wait-for-vercel-deployment` job, simplifying the workflow configuration.
> Fix: remove permissions for vercel preview job

- lib/hooks/usePwa.ts
N/A
Checks typeof window, if undefined returns unknown browser stats. 
Window is a global, client-side object from the browser. Therefore cannot be defined in a server-side hook or a dependency of useMemo(). This PR prevents errors due to undefined window on app initialization. Even with use-client, this does not ensure it won't run on server-side first: https://github.com/vercel/next.js/discussions/42319#discussioncomment-4033667.
Given the hook is called when the header is loaded and browser information is accessible after initialization, ie: if a user navigates anywhere, we should gain valuable metrics if 1 - users download the app after navigating anywhere on the site and 2 - if the browser is unknown, indicates users downloaded PWA upon first visit.
Future contributor issue: since …
> Fix: define window in usePWA.ts

- .github/workflows/cypress-release-test.yml
- package.json
- yarn.lock
This pull request updates dependencies in the `package.json` file to ensure compatibility and improve functionality. The changes include adding a new dependency and upgrading an existing one.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L8-R9): Added `brace-expansion` version `^2.0.1` to the resolutions section.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L99-R100): Upgraded `jest` from version `^29.7.0` to `^30.0.3`.
> update: brace-expansion and jest for vulnerabilities

- components/forms/RegisterForm.tsx
- cypress/integration/tests/therapy-usage.cy.tsx
- i18n/messages/auth/fr.json
This pull request introduces changes across three areas: functionality updates in the `RegisterForm` component, improvements to Cypress tests, and localization updates for French language support. Below is a summary of the most important changes grouped by theme.
* Added a return value (`true`) to the `validateAccessCode` function in `RegisterForm` to indicate successful validation. (`components/forms/RegisterForm.tsx`, [components/forms/RegisterForm.tsxR102](diffhunk://#diff-974d25db2b14be7deac45ae68d57458f11199898554484c589c65f80a28f9ab3R102))
* Added a `cy.wait(4000)` command in the Cypress test for therapy booking to address page rerendering issues during testing. (`cypress/integration/tests/therapy-usage.cy.tsx`, [cypress/integration/tests/therapy-usage.cy.tsxR73](diffhunk://#diff-c69 …
> fix: tests broken by notes from bloom issues

- components/cards/RelatedContentCard.tsx
- components/cards/ShortsCard.tsx
- components/layout/BaseLayout.tsx
- components/layout/PrimaryNavigationDrawerLinks.tsx
- components/layout/SecondaryNav.tsx
- components/layout/SecondaryNavigationDrawerLinks.tsx
- components/resources/ResourceCompleteButton.tsx
- components/session/SessionCompleteButton.tsx
- styles/theme.ts
Our style guide and designs use font weight 400 by default, with 500 being used sparingly.
Our theme was using too heavy a weight for some headings and components, these have now been reduced.
The `Open_Sans` used to import `600` weight and this is now replaced with `500` so it will fall back to 500 even if 600 was used. 500 was previously missing.
> Fix global font weights

- components/banner/FruitzRetirementBanner.tsx
- i18n/messages/shared/de.json
- i18n/messages/shared/en.json
- i18n/messages/shared/es.json
- i18n/messages/shared/fr.json
- i18n/messages/shared/hi.json
- i18n/messages/shared/pt.json
This pull request updates the `FruitzRetirementBanner` component to improve its functionality and modifies the associated translations to reflect updated messaging about the Fruitz x Bloom partnership. Key changes include adjustments to the banner's display logic, styling, and multilingual content updates.
* Updated the `showBanner` logic in `FruitzRetirementBanner.tsx` to include a new condition (`isFruitzWelcomePage`) that ensures the banner is displayed on Fruitz-specific welcome pages.
* Moved the `containerStyle` definition into the component and modified it to dynamically set the background color based on the `isFruitzWelcomePage` condition.
* Removed the unused `containerStyle` constant from the top of the file.
* Updated the `fruitzRetirementBanner.description` in all supported …
> feat: retire fruitz banner

- components/cards/ResourceCard.tsx
Fixes ResourceCard image position which was cutting off the image at the top
> fix resource card image position

- cypress/integration/tests/user-apply-a-code.cy.tsx
- lib/constants/partners.ts
Removes fruitz from all partners content (banner) but doesnt completely remove fruitz content from constants in case required in future.
> Remove fruitz from partner content

- components/cards/ResourceCard.tsx
- components/common/Carousel.tsx
- components/common/ResourceCarousel.tsx
Fixes/adds workaround for bug with nuka-carousel.
The issue: if a carousel slide only had <0.5 of the slide filled, its not recognised as a page, and the dots are hidden. Fixed by adding a calculation to add an extra ghost item for now.
> Fix carousel page bug
